// Code generated by protoc-gen-go.
// source: buy.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	buy.proto
	chat.proto
	login.proto
	room.proto
	user.proto
	vo.proto

It has these top-level messages:
	CBuy
	SBuy
	CWxpayOrder
	SWxpayOrder
	CWxpayQuery
	SWxpayQuery
	CApplePay
	SApplePay
	CShop
	SShop
	Shop
	CChatText
	SChatText
	CChatVoice
	SChatVoice
	SBroadcast
	CNotice
	SNotice
	Notice
	CLogin
	SLogin
	CRegist
	SRegist
	CWxLogin
	SWxLogin
	SLoginOut
	CEnterRoom
	SEnterRoom
	CCreateRoom
	SCreateRoom
	SCamein
	CLeave
	SLeave
	CKick
	SKick
	CReady
	SReady
	SDraw
	CDealer
	SDealer
	SPushDealer
	CBet
	SBet
	CNiu
	SNiu
	SGameover
	CLaunchVote
	SLaunchVote
	CVote
	SVote
	SVoteResult
	CGameRecord
	SGameRecord
	CEnterFreeRoom
	SEnterFreeRoom
	SFreeCamein
	CFreeDealer
	SFreeDealer
	CDealerList
	SDealerList
	CFreeSit
	SFreeSit
	CFreeBet
	SFreeBet
	SFreeGamestart
	SFreeGameover
	CFreeTrend
	SFreeTrend
	CEnterClassicRoom
	SEnterClassicRoom
	SClassicGameover
	SPubDraw
	CGetPrize
	SGetPrize
	CPrizeCards
	SPrizeCards
	CEnterZiRoom
	SEnterZiRoom
	CCreateZiRoom
	SCreateZiRoom
	SZiCamein
	SZiGameover
	CZiGameRecord
	SZiGameRecord
	SPushDeal
	SPushDealerDeal
	SPushDraw
	CPushDiscard
	SPushDiscard
	SPushAuto
	COperate
	SOperate
	SPushStatus
	CConfig
	SConfig
	CUserData
	SUserData
	CGetCurrency
	SGetCurrency
	CBuildAgent
	SBuildAgent
	SPushCurrency
	CBank
	SBank
	CPing
	SPing
	CBankrupts
	SBankrupts
	CPrizeList
	SPrizeList
	CPrizeDraw
	SPrizeDraw
	CPrizeBox
	SPrizeBox
	CClassicList
	SClassicList
	CVipList
	SVipList
	SPushVip
	UserData
	UserInfo
	RoomInfo
	Activity
	Prize
	Classic
	Vip
	VipInfo
	RoomUser
	RoomData
	RoomBets
	FreeUser
	FreeRoom
	RoomOver
	FreeRoomOver
	RoomScore
	ClassicOver
	OverList
	RoomVote
	RecordList
	DealerList
	FreeTrendList
	FreeTrend
	PrizeCard
	RoomCard
	RoomSeat
	ZiRoomOver
	ZiRoomRound
	ZiRecordList
	ZiRoomInfo
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 商城
type CBuy struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3000" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBuy) Reset()                    { *m = CBuy{} }
func (m *CBuy) String() string            { return proto.CompactTextString(m) }
func (*CBuy) ProtoMessage()               {}
func (*CBuy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_CBuy_Code uint32 = 3000

func (m *CBuy) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBuy_Code
}

func (m *CBuy) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SBuy struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3000" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBuy) Reset()                    { *m = SBuy{} }
func (m *SBuy) String() string            { return proto.CompactTextString(m) }
func (*SBuy) ProtoMessage()               {}
func (*SBuy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_SBuy_Code uint32 = 3000
const Default_SBuy_Error uint32 = 0

func (m *SBuy) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBuy_Code
}

func (m *SBuy) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SBuy) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBuy_Error
}

// 微信支付 - 下单
type CWxpayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3002" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Body             *string `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWxpayOrder) Reset()                    { *m = CWxpayOrder{} }
func (m *CWxpayOrder) String() string            { return proto.CompactTextString(m) }
func (*CWxpayOrder) ProtoMessage()               {}
func (*CWxpayOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_CWxpayOrder_Code uint32 = 3002

func (m *CWxpayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWxpayOrder_Code
}

func (m *CWxpayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CWxpayOrder) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type SWxpayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3002" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Payreq           *string `protobuf:"bytes,3,opt,name=payreq" json:"payreq,omitempty"`
	Orderid          *string `protobuf:"bytes,4,opt,name=orderid" json:"orderid,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWxpayOrder) Reset()                    { *m = SWxpayOrder{} }
func (m *SWxpayOrder) String() string            { return proto.CompactTextString(m) }
func (*SWxpayOrder) ProtoMessage()               {}
func (*SWxpayOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_SWxpayOrder_Code uint32 = 3002
const Default_SWxpayOrder_Error uint32 = 0

func (m *SWxpayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWxpayOrder_Code
}

func (m *SWxpayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SWxpayOrder) GetPayreq() string {
	if m != nil && m.Payreq != nil {
		return *m.Payreq
	}
	return ""
}

func (m *SWxpayOrder) GetOrderid() string {
	if m != nil && m.Orderid != nil {
		return *m.Orderid
	}
	return ""
}

func (m *SWxpayOrder) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWxpayOrder_Error
}

// 微信支付 - 查询
type CWxpayQuery struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3004" json:"code,omitempty"`
	Transid          *string `protobuf:"bytes,2,req,name=transid" json:"transid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWxpayQuery) Reset()                    { *m = CWxpayQuery{} }
func (m *CWxpayQuery) String() string            { return proto.CompactTextString(m) }
func (*CWxpayQuery) ProtoMessage()               {}
func (*CWxpayQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_CWxpayQuery_Code uint32 = 3004

func (m *CWxpayQuery) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWxpayQuery_Code
}

func (m *CWxpayQuery) GetTransid() string {
	if m != nil && m.Transid != nil {
		return *m.Transid
	}
	return ""
}

type SWxpayQuery struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3004" json:"code,omitempty"`
	Orderid          *string `protobuf:"bytes,2,opt,name=orderid" json:"orderid,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWxpayQuery) Reset()                    { *m = SWxpayQuery{} }
func (m *SWxpayQuery) String() string            { return proto.CompactTextString(m) }
func (*SWxpayQuery) ProtoMessage()               {}
func (*SWxpayQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

const Default_SWxpayQuery_Code uint32 = 3004
const Default_SWxpayQuery_Error uint32 = 0

func (m *SWxpayQuery) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWxpayQuery_Code
}

func (m *SWxpayQuery) GetOrderid() string {
	if m != nil && m.Orderid != nil {
		return *m.Orderid
	}
	return ""
}

func (m *SWxpayQuery) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SWxpayQuery) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWxpayQuery_Error
}

//  苹果支付
type CApplePay struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3006" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Receipt          *string `protobuf:"bytes,3,req,name=receipt" json:"receipt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CApplePay) Reset()                    { *m = CApplePay{} }
func (m *CApplePay) String() string            { return proto.CompactTextString(m) }
func (*CApplePay) ProtoMessage()               {}
func (*CApplePay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_CApplePay_Code uint32 = 3006

func (m *CApplePay) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CApplePay_Code
}

func (m *CApplePay) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CApplePay) GetReceipt() string {
	if m != nil && m.Receipt != nil {
		return *m.Receipt
	}
	return ""
}

type SApplePay struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3006" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SApplePay) Reset()                    { *m = SApplePay{} }
func (m *SApplePay) String() string            { return proto.CompactTextString(m) }
func (*SApplePay) ProtoMessage()               {}
func (*SApplePay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

const Default_SApplePay_Code uint32 = 3006
const Default_SApplePay_Error uint32 = 0

func (m *SApplePay) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SApplePay_Code
}

func (m *SApplePay) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SApplePay) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SApplePay_Error
}

// 商城
type CShop struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3010" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CShop) Reset()                    { *m = CShop{} }
func (m *CShop) String() string            { return proto.CompactTextString(m) }
func (*CShop) ProtoMessage()               {}
func (*CShop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

const Default_CShop_Code uint32 = 3010

func (m *CShop) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CShop_Code
}

type SShop struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3010" json:"code,omitempty"`
	List             []*Shop `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SShop) Reset()                    { *m = SShop{} }
func (m *SShop) String() string            { return proto.CompactTextString(m) }
func (*SShop) ProtoMessage()               {}
func (*SShop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

const Default_SShop_Code uint32 = 3010
const Default_SShop_Error uint32 = 0

func (m *SShop) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SShop_Code
}

func (m *SShop) GetList() []*Shop {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SShop) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SShop_Error
}

// 商品
type Shop struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Status           *uint32 `protobuf:"varint,2,req,name=Status" json:"Status,omitempty"`
	Propid           *uint32 `protobuf:"varint,3,req,name=Propid" json:"Propid,omitempty"`
	Payway           *uint32 `protobuf:"varint,4,req,name=Payway" json:"Payway,omitempty"`
	Number           *uint32 `protobuf:"varint,5,req,name=Number" json:"Number,omitempty"`
	Price            *uint32 `protobuf:"varint,6,req,name=Price" json:"Price,omitempty"`
	Name             *string `protobuf:"bytes,7,req,name=Name" json:"Name,omitempty"`
	Info             *string `protobuf:"bytes,8,req,name=Info" json:"Info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Shop) Reset()                    { *m = Shop{} }
func (m *Shop) String() string            { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()               {}
func (*Shop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Shop) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Shop) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Shop) GetPropid() uint32 {
	if m != nil && m.Propid != nil {
		return *m.Propid
	}
	return 0
}

func (m *Shop) GetPayway() uint32 {
	if m != nil && m.Payway != nil {
		return *m.Payway
	}
	return 0
}

func (m *Shop) GetNumber() uint32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *Shop) GetPrice() uint32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Shop) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*CBuy)(nil), "protocol.CBuy")
	proto.RegisterType((*SBuy)(nil), "protocol.SBuy")
	proto.RegisterType((*CWxpayOrder)(nil), "protocol.CWxpayOrder")
	proto.RegisterType((*SWxpayOrder)(nil), "protocol.SWxpayOrder")
	proto.RegisterType((*CWxpayQuery)(nil), "protocol.CWxpayQuery")
	proto.RegisterType((*SWxpayQuery)(nil), "protocol.SWxpayQuery")
	proto.RegisterType((*CApplePay)(nil), "protocol.CApplePay")
	proto.RegisterType((*SApplePay)(nil), "protocol.SApplePay")
	proto.RegisterType((*CShop)(nil), "protocol.CShop")
	proto.RegisterType((*SShop)(nil), "protocol.SShop")
	proto.RegisterType((*Shop)(nil), "protocol.Shop")
}

func init() { proto.RegisterFile("buy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x3d, 0x8f, 0x9b, 0x40,
	0x10, 0x15, 0xb0, 0xd8, 0x66, 0x2c, 0xbb, 0x58, 0x45, 0x09, 0xa5, 0xb3, 0x15, 0x95, 0x45, 0x9c,
	0x28, 0x45, 0x3a, 0x87, 0x2a, 0x8a, 0xe4, 0x0f, 0x28, 0xd2, 0x45, 0xc2, 0xb0, 0x51, 0x90, 0xb0,
	0x97, 0x2c, 0xa0, 0x84, 0x36, 0xbf, 0xe9, 0x7e, 0xe0, 0xed, 0x17, 0x67, 0x9d, 0x0f, 0x5b, 0x77,
	0x57, 0x31, 0xef, 0xed, 0xce, 0xe3, 0xcd, 0xce, 0x0c, 0x78, 0x87, 0xb6, 0x5b, 0x56, 0x9c, 0x35,
	0x0c, 0x4f, 0xd4, 0x27, 0x63, 0x25, 0x09, 0x01, 0x45, 0x5f, 0xdb, 0x0e, 0xfb, 0x80, 0x32, 0x96,
	0x53, 0xdf, 0x5a, 0x58, 0xc1, 0xec, 0x0b, 0xfa, 0x18, 0x86, 0x61, 0xac, 0x18, 0x3c, 0x07, 0xbb,
	0xc8, 0x7d, 0x7b, 0x61, 0x07, 0xb3, 0x58, 0x44, 0x64, 0x0f, 0x28, 0xb9, 0x9d, 0xf1, 0x16, 0x46,
	0x9c, 0xd6, 0x6d, 0xd9, 0x88, 0x2c, 0x71, 0x16, 0x1b, 0x84, 0xdf, 0x81, 0x4b, 0x39, 0x67, 0xdc,
	0x77, 0x54, 0x8a, 0x15, 0xc6, 0x1a, 0x93, 0xef, 0x30, 0x8d, 0x7e, 0xfc, 0xab, 0xd2, 0x6e, 0xcb,
	0x73, 0xca, 0x07, 0x94, 0x57, 0xc3, 0x5e, 0x30, 0x06, 0x74, 0x60, 0x79, 0x27, 0x04, 0xed, 0xc0,
	0x8b, 0x55, 0x4c, 0xfe, 0x5b, 0x30, 0x4d, 0x5e, 0xa4, 0x66, 0x19, 0x35, 0xe1, 0x5b, 0x64, 0x71,
	0xfa, 0x47, 0x19, 0xf4, 0x62, 0x83, 0x84, 0xc2, 0x98, 0x49, 0x29, 0x71, 0x19, 0xa9, 0x83, 0x1e,
	0x9e, 0x2b, 0x72, 0x2f, 0x2a, 0x5a, 0xf7, 0x15, 0xed, 0x5b, 0xca, 0x87, 0xde, 0xea, 0x93, 0xf1,
	0x20, 0xb4, 0x1b, 0x9e, 0x9e, 0x6a, 0x53, 0x96, 0xd0, 0x36, 0x90, 0xf0, 0xbe, 0x8c, 0x67, 0x48,
	0xf4, 0xf6, 0xec, 0xc7, 0xf6, 0xce, 0x8d, 0x70, 0x86, 0x1b, 0x81, 0x2e, 0x6c, 0x6f, 0xc1, 0x8b,
	0xd6, 0x55, 0x55, 0xd2, 0x5d, 0x3a, 0xf4, 0xc7, 0xcf, 0x57, 0xda, 0x20, 0x1c, 0x70, 0x9a, 0xd1,
	0xa2, 0x6a, 0x4c, 0x27, 0x7a, 0x48, 0x36, 0xe0, 0x25, 0xaf, 0x10, 0xbc, 0x3a, 0x29, 0xef, 0xc1,
	0x8d, 0x92, 0xdf, 0xac, 0x7a, 0xaa, 0xf5, 0xc1, 0x4c, 0x1f, 0xf9, 0x09, 0x6e, 0x72, 0xfb, 0x0a,
	0x26, 0x80, 0xca, 0xa2, 0x96, 0xe3, 0xe9, 0x04, 0xd3, 0xd5, 0x7c, 0xd9, 0x6f, 0xc3, 0x52, 0xe6,
	0xc5, 0xea, 0xec, 0xba, 0x85, 0x3b, 0x4b, 0x2c, 0x80, 0xd4, 0xd7, 0xa6, 0xad, 0x07, 0xd3, 0xe2,
	0xb5, 0x93, 0x26, 0x6d, 0xda, 0xda, 0x14, 0x62, 0x90, 0xe4, 0x77, 0x9c, 0x55, 0xe2, 0xae, 0xa3,
	0x79, 0x8d, 0x14, 0x9f, 0x76, 0x7f, 0xd3, 0x4e, 0xb4, 0x41, 0xf3, 0x0a, 0x49, 0x7e, 0xd3, 0x1e,
	0x0f, 0x54, 0x4e, 0x95, 0xe2, 0x35, 0xc2, 0x6f, 0xc0, 0xdd, 0xf1, 0x22, 0xa3, 0xfe, 0x48, 0xd1,
	0x1a, 0xc8, 0x15, 0xd8, 0xa4, 0x47, 0xea, 0x8f, 0xf5, 0x0a, 0xc8, 0x58, 0x72, 0xdf, 0x4e, 0xbf,
	0x98, 0x3f, 0xd1, 0x9c, 0x8c, 0xef, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x71, 0xfb, 0xa2, 0xfe,
	0x03, 0x00, 0x00,
}
