// Code generated by protoc-gen-go.
// source: room.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 进入房间
type CEnterRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4000" json:"code,omitempty"`
	Invitecode       *string `protobuf:"bytes,2,req,name=invitecode" json:"invitecode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CEnterRoom) Reset()                    { *m = CEnterRoom{} }
func (m *CEnterRoom) String() string            { return proto.CompactTextString(m) }
func (*CEnterRoom) ProtoMessage()               {}
func (*CEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

const Default_CEnterRoom_Code uint32 = 4000

func (m *CEnterRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CEnterRoom_Code
}

func (m *CEnterRoom) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

type SEnterRoom struct {
	Code             *uint32     `protobuf:"varint,1,opt,name=code,def=4000" json:"code,omitempty"`
	Roominfo         *RoomData   `protobuf:"bytes,2,req,name=roominfo" json:"roominfo,omitempty"`
	Userinfo         []*RoomUser `protobuf:"bytes,3,rep,name=userinfo" json:"userinfo,omitempty"`
	Voteinfo         *RoomVote   `protobuf:"bytes,4,opt,name=voteinfo" json:"voteinfo,omitempty"`
	Betsinfo         []*RoomBets `protobuf:"bytes,5,rep,name=betsinfo" json:"betsinfo,omitempty"`
	Error            *uint32     `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SEnterRoom) Reset()                    { *m = SEnterRoom{} }
func (m *SEnterRoom) String() string            { return proto.CompactTextString(m) }
func (*SEnterRoom) ProtoMessage()               {}
func (*SEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

const Default_SEnterRoom_Code uint32 = 4000
const Default_SEnterRoom_Error uint32 = 0

func (m *SEnterRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SEnterRoom_Code
}

func (m *SEnterRoom) GetRoominfo() *RoomData {
	if m != nil {
		return m.Roominfo
	}
	return nil
}

func (m *SEnterRoom) GetUserinfo() []*RoomUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SEnterRoom) GetVoteinfo() *RoomVote {
	if m != nil {
		return m.Voteinfo
	}
	return nil
}

func (m *SEnterRoom) GetBetsinfo() []*RoomBets {
	if m != nil {
		return m.Betsinfo
	}
	return nil
}

func (m *SEnterRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SEnterRoom_Error
}

// 创建房间
type CCreateRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4001" json:"code,omitempty"`
	Rname            *string `protobuf:"bytes,2,req,name=rname" json:"rname,omitempty"`
	Rtype            *uint32 `protobuf:"varint,3,req,name=rtype" json:"rtype,omitempty"`
	Ante             *uint32 `protobuf:"varint,4,req,name=ante" json:"ante,omitempty"`
	Round            *uint32 `protobuf:"varint,5,req,name=round" json:"round,omitempty"`
	Payment          *uint32 `protobuf:"varint,6,req,name=payment" json:"payment,omitempty"`
	Count            *uint32 `protobuf:"varint,7,req,name=count" json:"count,omitempty"`
	Chat             *uint32 `protobuf:"varint,8,opt,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCreateRoom) Reset()                    { *m = CCreateRoom{} }
func (m *CCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*CCreateRoom) ProtoMessage()               {}
func (*CCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

const Default_CCreateRoom_Code uint32 = 4001

func (m *CCreateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CCreateRoom_Code
}

func (m *CCreateRoom) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *CCreateRoom) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *CCreateRoom) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *CCreateRoom) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *CCreateRoom) GetPayment() uint32 {
	if m != nil && m.Payment != nil {
		return *m.Payment
	}
	return 0
}

func (m *CCreateRoom) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *CCreateRoom) GetChat() uint32 {
	if m != nil && m.Chat != nil {
		return *m.Chat
	}
	return 0
}

// 返回房间数据,
type SCreateRoom struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=4001" json:"code,omitempty"`
	Rdata            *RoomData `protobuf:"bytes,2,opt,name=rdata" json:"rdata,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCreateRoom) Reset()                    { *m = SCreateRoom{} }
func (m *SCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*SCreateRoom) ProtoMessage()               {}
func (*SCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

const Default_SCreateRoom_Code uint32 = 4001
const Default_SCreateRoom_Error uint32 = 0

func (m *SCreateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SCreateRoom_Code
}

func (m *SCreateRoom) GetRdata() *RoomData {
	if m != nil {
		return m.Rdata
	}
	return nil
}

func (m *SCreateRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SCreateRoom_Error
}

// 其他玩家进入房间
type SCamein struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=4003" json:"code,omitempty"`
	Userinfo         *RoomUser `protobuf:"bytes,2,req,name=userinfo" json:"userinfo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCamein) Reset()                    { *m = SCamein{} }
func (m *SCamein) String() string            { return proto.CompactTextString(m) }
func (*SCamein) ProtoMessage()               {}
func (*SCamein) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

const Default_SCamein_Code uint32 = 4003

func (m *SCamein) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SCamein_Code
}

func (m *SCamein) GetUserinfo() *RoomUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

// 离开房间
type CLeave struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4004" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CLeave) Reset()                    { *m = CLeave{} }
func (m *CLeave) String() string            { return proto.CompactTextString(m) }
func (*CLeave) ProtoMessage()               {}
func (*CLeave) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

const Default_CLeave_Code uint32 = 4004

func (m *CLeave) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CLeave_Code
}

type SLeave struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4004" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Userid           *string `protobuf:"bytes,3,opt,name=userid" json:"userid,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SLeave) Reset()                    { *m = SLeave{} }
func (m *SLeave) String() string            { return proto.CompactTextString(m) }
func (*SLeave) ProtoMessage()               {}
func (*SLeave) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

const Default_SLeave_Code uint32 = 4004
const Default_SLeave_Error uint32 = 0

func (m *SLeave) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SLeave_Code
}

func (m *SLeave) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SLeave) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SLeave) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SLeave_Error
}

// 踢人
type CKick struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4005" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CKick) Reset()                    { *m = CKick{} }
func (m *CKick) String() string            { return proto.CompactTextString(m) }
func (*CKick) ProtoMessage()               {}
func (*CKick) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

const Default_CKick_Code uint32 = 4005

func (m *CKick) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CKick_Code
}

func (m *CKick) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

type SKick struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4005" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Userid           *string `protobuf:"bytes,3,opt,name=userid" json:"userid,omitempty"`
	Result           *uint32 `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SKick) Reset()                    { *m = SKick{} }
func (m *SKick) String() string            { return proto.CompactTextString(m) }
func (*SKick) ProtoMessage()               {}
func (*SKick) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

const Default_SKick_Code uint32 = 4005
const Default_SKick_Error uint32 = 0

func (m *SKick) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SKick_Code
}

func (m *SKick) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SKick) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SKick) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SKick) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SKick_Error
}

// 1.准备游戏(准备完成开始游戏时状态切为发牌)
type CReady struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4006" json:"code,omitempty"`
	Ready            *bool   `protobuf:"varint,2,req,name=ready" json:"ready,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CReady) Reset()                    { *m = CReady{} }
func (m *CReady) String() string            { return proto.CompactTextString(m) }
func (*CReady) ProtoMessage()               {}
func (*CReady) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

const Default_CReady_Code uint32 = 4006

func (m *CReady) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CReady_Code
}

func (m *CReady) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

type SReady struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4006" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Ready            *bool   `protobuf:"varint,3,opt,name=ready" json:"ready,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SReady) Reset()                    { *m = SReady{} }
func (m *SReady) String() string            { return proto.CompactTextString(m) }
func (*SReady) ProtoMessage()               {}
func (*SReady) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

const Default_SReady_Code uint32 = 4006
const Default_SReady_Error uint32 = 0

func (m *SReady) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SReady_Code
}

func (m *SReady) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SReady) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *SReady) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SReady_Error
}

// 2.发牌(全部准备后或达到开始条件,发完状态切为抢庄)
type SDraw struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4007" json:"code,omitempty"`
	Seat             *uint32  `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	State            *uint32  `protobuf:"varint,3,req,name=state" json:"state,omitempty"`
	Cards            []uint32 `protobuf:"varint,4,rep,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SDraw) Reset()                    { *m = SDraw{} }
func (m *SDraw) String() string            { return proto.CompactTextString(m) }
func (*SDraw) ProtoMessage()               {}
func (*SDraw) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

const Default_SDraw_Code uint32 = 4007

func (m *SDraw) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDraw_Code
}

func (m *SDraw) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SDraw) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SDraw) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 3.开始抢庄(发完第一轮牌后,抢完切为下注)
type CDealer struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4008" json:"code,omitempty"`
	Dealer           *bool   `protobuf:"varint,2,req,name=dealer" json:"dealer,omitempty"`
	Num              *uint32 `protobuf:"varint,3,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDealer) Reset()                    { *m = CDealer{} }
func (m *CDealer) String() string            { return proto.CompactTextString(m) }
func (*CDealer) ProtoMessage()               {}
func (*CDealer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

const Default_CDealer_Code uint32 = 4008

func (m *CDealer) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CDealer_Code
}

func (m *CDealer) GetDealer() bool {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return false
}

func (m *CDealer) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type SDealer struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4008" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Dealer           *bool   `protobuf:"varint,3,req,name=dealer" json:"dealer,omitempty"`
	Num              *uint32 `protobuf:"varint,4,opt,name=num" json:"num,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDealer) Reset()                    { *m = SDealer{} }
func (m *SDealer) String() string            { return proto.CompactTextString(m) }
func (*SDealer) ProtoMessage()               {}
func (*SDealer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

const Default_SDealer_Code uint32 = 4008
const Default_SDealer_Error uint32 = 0

func (m *SDealer) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDealer_Code
}

func (m *SDealer) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SDealer) GetDealer() bool {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return false
}

func (m *SDealer) GetNum() uint32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *SDealer) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDealer_Error
}

// 完成抢庄,推送庄家位置
type SPushDealer struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4009" json:"code,omitempty"`
	Dealer           *uint32 `protobuf:"varint,2,req,name=dealer" json:"dealer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPushDealer) Reset()                    { *m = SPushDealer{} }
func (m *SPushDealer) String() string            { return proto.CompactTextString(m) }
func (*SPushDealer) ProtoMessage()               {}
func (*SPushDealer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

const Default_SPushDealer_Code uint32 = 4009

func (m *SPushDealer) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushDealer_Code
}

func (m *SPushDealer) GetDealer() uint32 {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return 0
}

// 4.玩家下注(抢庄完成后),下注完成后再步骤2发牌
type CBet struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4010" json:"code,omitempty"`
	Seatbet          *uint32 `protobuf:"varint,2,opt,name=seatbet" json:"seatbet,omitempty"`
	Value            *uint32 `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBet) Reset()                    { *m = CBet{} }
func (m *CBet) String() string            { return proto.CompactTextString(m) }
func (*CBet) ProtoMessage()               {}
func (*CBet) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

const Default_CBet_Code uint32 = 4010

func (m *CBet) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBet_Code
}

func (m *CBet) GetSeatbet() uint32 {
	if m != nil && m.Seatbet != nil {
		return *m.Seatbet
	}
	return 0
}

func (m *CBet) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type SBet struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4010" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Seatbet          *uint32 `protobuf:"varint,3,opt,name=seatbet" json:"seatbet,omitempty"`
	Value            *uint32 `protobuf:"varint,4,req,name=value" json:"value,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBet) Reset()                    { *m = SBet{} }
func (m *SBet) String() string            { return proto.CompactTextString(m) }
func (*SBet) ProtoMessage()               {}
func (*SBet) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

const Default_SBet_Code uint32 = 4010
const Default_SBet_Error uint32 = 0

func (m *SBet) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBet_Code
}

func (m *SBet) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SBet) GetSeatbet() uint32 {
	if m != nil && m.Seatbet != nil {
		return *m.Seatbet
	}
	return 0
}

func (m *SBet) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SBet) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBet_Error
}

// 5.玩家组合牌提交
type CNiu struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4011" json:"code,omitempty"`
	Value            *uint32  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Cards            []uint32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CNiu) Reset()                    { *m = CNiu{} }
func (m *CNiu) String() string            { return proto.CompactTextString(m) }
func (*CNiu) ProtoMessage()               {}
func (*CNiu) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

const Default_CNiu_Code uint32 = 4011

func (m *CNiu) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CNiu_Code
}

func (m *CNiu) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *CNiu) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 广播提交结果
type SNiu struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4011" json:"code,omitempty"`
	Seat             *uint32  `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Value            *uint32  `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	Cards            []uint32 `protobuf:"varint,4,rep,name=cards" json:"cards,omitempty"`
	Error            *uint32  `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SNiu) Reset()                    { *m = SNiu{} }
func (m *SNiu) String() string            { return proto.CompactTextString(m) }
func (*SNiu) ProtoMessage()               {}
func (*SNiu) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

const Default_SNiu_Code uint32 = 4011
const Default_SNiu_Error uint32 = 0

func (m *SNiu) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SNiu_Code
}

func (m *SNiu) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SNiu) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SNiu) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SNiu) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SNiu_Error
}

// 结算广播接口，游戏结束
type SGameover struct {
	Code             *uint32     `protobuf:"varint,1,opt,name=code,def=4012" json:"code,omitempty"`
	Dealer           *uint32     `protobuf:"varint,2,req,name=dealer" json:"dealer,omitempty"`
	Round            *uint32     `protobuf:"varint,3,req,name=round" json:"round,omitempty"`
	Data             []*RoomOver `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	List             []*OverList `protobuf:"bytes,5,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SGameover) Reset()                    { *m = SGameover{} }
func (m *SGameover) String() string            { return proto.CompactTextString(m) }
func (*SGameover) ProtoMessage()               {}
func (*SGameover) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

const Default_SGameover_Code uint32 = 4012

func (m *SGameover) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGameover_Code
}

func (m *SGameover) GetDealer() uint32 {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return 0
}

func (m *SGameover) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *SGameover) GetData() []*RoomOver {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SGameover) GetList() []*OverList {
	if m != nil {
		return m.List
	}
	return nil
}

// 私人局,发起投票申请解散房间
type CLaunchVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4016" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CLaunchVote) Reset()                    { *m = CLaunchVote{} }
func (m *CLaunchVote) String() string            { return proto.CompactTextString(m) }
func (*CLaunchVote) ProtoMessage()               {}
func (*CLaunchVote) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

const Default_CLaunchVote_Code uint32 = 4016

func (m *CLaunchVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CLaunchVote_Code
}

type SLaunchVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4016" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SLaunchVote) Reset()                    { *m = SLaunchVote{} }
func (m *SLaunchVote) String() string            { return proto.CompactTextString(m) }
func (*SLaunchVote) ProtoMessage()               {}
func (*SLaunchVote) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

const Default_SLaunchVote_Code uint32 = 4016

func (m *SLaunchVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SLaunchVote_Code
}

func (m *SLaunchVote) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SLaunchVote) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

// 私人局,发起投票,投票解散房间,如果投票成功，服务器主动推送SKick协议，并且reason字段值为1
type CVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4017" json:"code,omitempty"`
	Vote             *uint32 `protobuf:"varint,2,req,name=vote" json:"vote,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CVote) Reset()                    { *m = CVote{} }
func (m *CVote) String() string            { return proto.CompactTextString(m) }
func (*CVote) ProtoMessage()               {}
func (*CVote) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{22} }

const Default_CVote_Code uint32 = 4017

func (m *CVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CVote_Code
}

func (m *CVote) GetVote() uint32 {
	if m != nil && m.Vote != nil {
		return *m.Vote
	}
	return 0
}

type SVote struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4017" json:"code,omitempty"`
	Vote             *uint32 `protobuf:"varint,2,req,name=vote" json:"vote,omitempty"`
	Seat             *uint32 `protobuf:"varint,3,req,name=seat" json:"seat,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SVote) Reset()                    { *m = SVote{} }
func (m *SVote) String() string            { return proto.CompactTextString(m) }
func (*SVote) ProtoMessage()               {}
func (*SVote) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{23} }

const Default_SVote_Code uint32 = 4017

func (m *SVote) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SVote_Code
}

func (m *SVote) GetVote() uint32 {
	if m != nil && m.Vote != nil {
		return *m.Vote
	}
	return 0
}

func (m *SVote) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SVote) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

// 投票解散房间事件结果,服务器主动推送
type SVoteResult struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4018" json:"code,omitempty"`
	Vote             *uint32 `protobuf:"varint,2,req,name=vote" json:"vote,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SVoteResult) Reset()                    { *m = SVoteResult{} }
func (m *SVoteResult) String() string            { return proto.CompactTextString(m) }
func (*SVoteResult) ProtoMessage()               {}
func (*SVoteResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{24} }

const Default_SVoteResult_Code uint32 = 4018

func (m *SVoteResult) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SVoteResult_Code
}

func (m *SVoteResult) GetVote() uint32 {
	if m != nil && m.Vote != nil {
		return *m.Vote
	}
	return 0
}

// 个人牌局记录,默认最近30场
type CGameRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4020" json:"code,omitempty"`
	Page             *uint32 `protobuf:"varint,2,req,name=page" json:"page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGameRecord) Reset()                    { *m = CGameRecord{} }
func (m *CGameRecord) String() string            { return proto.CompactTextString(m) }
func (*CGameRecord) ProtoMessage()               {}
func (*CGameRecord) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{25} }

const Default_CGameRecord_Code uint32 = 4020

func (m *CGameRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CGameRecord_Code
}

func (m *CGameRecord) GetPage() uint32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

type SGameRecord struct {
	Code             *uint32       `protobuf:"varint,1,opt,name=code,def=4020" json:"code,omitempty"`
	List             []*RecordList `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SGameRecord) Reset()                    { *m = SGameRecord{} }
func (m *SGameRecord) String() string            { return proto.CompactTextString(m) }
func (*SGameRecord) ProtoMessage()               {}
func (*SGameRecord) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{26} }

const Default_SGameRecord_Code uint32 = 4020

func (m *SGameRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGameRecord_Code
}

func (m *SGameRecord) GetList() []*RecordList {
	if m != nil {
		return m.List
	}
	return nil
}

// 进入房间
type CEnterFreeRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4040" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CEnterFreeRoom) Reset()                    { *m = CEnterFreeRoom{} }
func (m *CEnterFreeRoom) String() string            { return proto.CompactTextString(m) }
func (*CEnterFreeRoom) ProtoMessage()               {}
func (*CEnterFreeRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{27} }

const Default_CEnterFreeRoom_Code uint32 = 4040

func (m *CEnterFreeRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CEnterFreeRoom_Code
}

type SEnterFreeRoom struct {
	Code             *uint32     `protobuf:"varint,1,opt,name=code,def=4040" json:"code,omitempty"`
	Roominfo         *FreeRoom   `protobuf:"bytes,2,req,name=roominfo" json:"roominfo,omitempty"`
	Userinfo         []*FreeUser `protobuf:"bytes,3,rep,name=userinfo" json:"userinfo,omitempty"`
	Betsinfo         []*RoomBets `protobuf:"bytes,5,rep,name=betsinfo" json:"betsinfo,omitempty"`
	Error            *uint32     `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SEnterFreeRoom) Reset()                    { *m = SEnterFreeRoom{} }
func (m *SEnterFreeRoom) String() string            { return proto.CompactTextString(m) }
func (*SEnterFreeRoom) ProtoMessage()               {}
func (*SEnterFreeRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{28} }

const Default_SEnterFreeRoom_Code uint32 = 4040
const Default_SEnterFreeRoom_Error uint32 = 0

func (m *SEnterFreeRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SEnterFreeRoom_Code
}

func (m *SEnterFreeRoom) GetRoominfo() *FreeRoom {
	if m != nil {
		return m.Roominfo
	}
	return nil
}

func (m *SEnterFreeRoom) GetUserinfo() []*FreeUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SEnterFreeRoom) GetBetsinfo() []*RoomBets {
	if m != nil {
		return m.Betsinfo
	}
	return nil
}

func (m *SEnterFreeRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SEnterFreeRoom_Error
}

// 其他玩家进入房间
type SFreeCamein struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=4041" json:"code,omitempty"`
	Userinfo         *FreeUser `protobuf:"bytes,2,req,name=userinfo" json:"userinfo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SFreeCamein) Reset()                    { *m = SFreeCamein{} }
func (m *SFreeCamein) String() string            { return proto.CompactTextString(m) }
func (*SFreeCamein) ProtoMessage()               {}
func (*SFreeCamein) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{29} }

const Default_SFreeCamein_Code uint32 = 4041

func (m *SFreeCamein) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeCamein_Code
}

func (m *SFreeCamein) GetUserinfo() *FreeUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

// 3.选择上庄，下庄
type CFreeDealer struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4042" json:"code,omitempty"`
	State            *uint32 `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	Coin             *uint32 `protobuf:"varint,3,opt,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFreeDealer) Reset()                    { *m = CFreeDealer{} }
func (m *CFreeDealer) String() string            { return proto.CompactTextString(m) }
func (*CFreeDealer) ProtoMessage()               {}
func (*CFreeDealer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{30} }

const Default_CFreeDealer_Code uint32 = 4042

func (m *CFreeDealer) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CFreeDealer_Code
}

func (m *CFreeDealer) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *CFreeDealer) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

type SFreeDealer struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4042" json:"code,omitempty"`
	State            *uint32 `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	Dealer           *string `protobuf:"bytes,3,req,name=dealer" json:"dealer,omitempty"`
	Userid           *string `protobuf:"bytes,4,req,name=userid" json:"userid,omitempty"`
	Nickname         *string `protobuf:"bytes,5,req,name=nickname" json:"nickname,omitempty"`
	Coin             *uint32 `protobuf:"varint,6,opt,name=coin" json:"coin,omitempty"`
	Error            *uint32 `protobuf:"varint,7,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFreeDealer) Reset()                    { *m = SFreeDealer{} }
func (m *SFreeDealer) String() string            { return proto.CompactTextString(m) }
func (*SFreeDealer) ProtoMessage()               {}
func (*SFreeDealer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{31} }

const Default_SFreeDealer_Code uint32 = 4042
const Default_SFreeDealer_Error uint32 = 0

func (m *SFreeDealer) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeDealer_Code
}

func (m *SFreeDealer) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SFreeDealer) GetDealer() string {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return ""
}

func (m *SFreeDealer) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SFreeDealer) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *SFreeDealer) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *SFreeDealer) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SFreeDealer_Error
}

// 3.上庄列表
type CDealerList struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4043" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDealerList) Reset()                    { *m = CDealerList{} }
func (m *CDealerList) String() string            { return proto.CompactTextString(m) }
func (*CDealerList) ProtoMessage()               {}
func (*CDealerList) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{32} }

const Default_CDealerList_Code uint32 = 4043

func (m *CDealerList) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CDealerList_Code
}

type SDealerList struct {
	Code             *uint32       `protobuf:"varint,1,opt,name=code,def=4043" json:"code,omitempty"`
	List             []*DealerList `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32       `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SDealerList) Reset()                    { *m = SDealerList{} }
func (m *SDealerList) String() string            { return proto.CompactTextString(m) }
func (*SDealerList) ProtoMessage()               {}
func (*SDealerList) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{33} }

const Default_SDealerList_Code uint32 = 4043
const Default_SDealerList_Error uint32 = 0

func (m *SDealerList) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SDealerList_Code
}

func (m *SDealerList) GetList() []*DealerList {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SDealerList) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SDealerList_Error
}

// 4.玩家入坐,站起
type CFreeSit struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4044" json:"code,omitempty"`
	State            *bool   `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Seat             *uint32 `protobuf:"varint,3,req,name=seat" json:"seat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFreeSit) Reset()                    { *m = CFreeSit{} }
func (m *CFreeSit) String() string            { return proto.CompactTextString(m) }
func (*CFreeSit) ProtoMessage()               {}
func (*CFreeSit) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{34} }

const Default_CFreeSit_Code uint32 = 4044

func (m *CFreeSit) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CFreeSit_Code
}

func (m *CFreeSit) GetState() bool {
	if m != nil && m.State != nil {
		return *m.State
	}
	return false
}

func (m *CFreeSit) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

type SFreeSit struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4044" json:"code,omitempty"`
	State            *bool   `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Seat             *uint32 `protobuf:"varint,3,req,name=seat" json:"seat,omitempty"`
	Userid           *string `protobuf:"bytes,4,req,name=userid" json:"userid,omitempty"`
	Nickname         *string `protobuf:"bytes,5,req,name=nickname" json:"nickname,omitempty"`
	Photo            *string `protobuf:"bytes,6,req,name=photo" json:"photo,omitempty"`
	Coin             *uint32 `protobuf:"varint,7,req,name=coin" json:"coin,omitempty"`
	Error            *uint32 `protobuf:"varint,8,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFreeSit) Reset()                    { *m = SFreeSit{} }
func (m *SFreeSit) String() string            { return proto.CompactTextString(m) }
func (*SFreeSit) ProtoMessage()               {}
func (*SFreeSit) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{35} }

const Default_SFreeSit_Code uint32 = 4044
const Default_SFreeSit_Error uint32 = 0

func (m *SFreeSit) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeSit_Code
}

func (m *SFreeSit) GetState() bool {
	if m != nil && m.State != nil {
		return *m.State
	}
	return false
}

func (m *SFreeSit) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SFreeSit) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SFreeSit) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *SFreeSit) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *SFreeSit) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *SFreeSit) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SFreeSit_Error
}

// 4.玩家下注
type CFreeBet struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4046" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Value            *uint32 `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFreeBet) Reset()                    { *m = CFreeBet{} }
func (m *CFreeBet) String() string            { return proto.CompactTextString(m) }
func (*CFreeBet) ProtoMessage()               {}
func (*CFreeBet) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{36} }

const Default_CFreeBet_Code uint32 = 4046

func (m *CFreeBet) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CFreeBet_Code
}

func (m *CFreeBet) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *CFreeBet) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type SFreeBet struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4046" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	Beseat           *uint32 `protobuf:"varint,3,req,name=beseat" json:"beseat,omitempty"`
	Value            *uint32 `protobuf:"varint,4,req,name=value" json:"value,omitempty"`
	Userid           *string `protobuf:"bytes,5,req,name=userid" json:"userid,omitempty"`
	Coin             *uint32 `protobuf:"varint,6,req,name=coin" json:"coin,omitempty"`
	Bets             *uint32 `protobuf:"varint,7,req,name=bets" json:"bets,omitempty"`
	Error            *uint32 `protobuf:"varint,8,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFreeBet) Reset()                    { *m = SFreeBet{} }
func (m *SFreeBet) String() string            { return proto.CompactTextString(m) }
func (*SFreeBet) ProtoMessage()               {}
func (*SFreeBet) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{37} }

const Default_SFreeBet_Code uint32 = 4046
const Default_SFreeBet_Error uint32 = 0

func (m *SFreeBet) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeBet_Code
}

func (m *SFreeBet) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SFreeBet) GetBeseat() uint32 {
	if m != nil && m.Beseat != nil {
		return *m.Beseat
	}
	return 0
}

func (m *SFreeBet) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SFreeBet) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *SFreeBet) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *SFreeBet) GetBets() uint32 {
	if m != nil && m.Bets != nil {
		return *m.Bets
	}
	return 0
}

func (m *SFreeBet) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SFreeBet_Error
}

// 结算广播接口，游戏开始
type SFreeGamestart struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4048" json:"code,omitempty"`
	State            *uint32 `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Dealer           *string `protobuf:"bytes,3,req,name=dealer" json:"dealer,omitempty"`
	Coin             *uint32 `protobuf:"varint,4,req,name=coin" json:"coin,omitempty"`
	Photo            *string `protobuf:"bytes,5,req,name=photo" json:"photo,omitempty"`
	DealerNum        *uint32 `protobuf:"varint,6,req,name=dealerNum" json:"dealerNum,omitempty"`
	LeftDealerNum    *uint32 `protobuf:"varint,7,req,name=leftDealerNum" json:"leftDealerNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFreeGamestart) Reset()                    { *m = SFreeGamestart{} }
func (m *SFreeGamestart) String() string            { return proto.CompactTextString(m) }
func (*SFreeGamestart) ProtoMessage()               {}
func (*SFreeGamestart) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{38} }

const Default_SFreeGamestart_Code uint32 = 4048

func (m *SFreeGamestart) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeGamestart_Code
}

func (m *SFreeGamestart) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SFreeGamestart) GetDealer() string {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return ""
}

func (m *SFreeGamestart) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *SFreeGamestart) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *SFreeGamestart) GetDealerNum() uint32 {
	if m != nil && m.DealerNum != nil {
		return *m.DealerNum
	}
	return 0
}

func (m *SFreeGamestart) GetLeftDealerNum() uint32 {
	if m != nil && m.LeftDealerNum != nil {
		return *m.LeftDealerNum
	}
	return 0
}

// 结算广播接口，游戏结束
type SFreeGameover struct {
	Code             *uint32         `protobuf:"varint,1,opt,name=code,def=4050" json:"code,omitempty"`
	State            *uint32         `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Dealer           *string         `protobuf:"bytes,3,req,name=dealer" json:"dealer,omitempty"`
	DealerNum        *uint32         `protobuf:"varint,4,req,name=dealerNum" json:"dealerNum,omitempty"`
	LeftDealerNum    *uint32         `protobuf:"varint,5,req,name=leftDealerNum" json:"leftDealerNum,omitempty"`
	Coin             *uint32         `protobuf:"varint,6,req,name=coin" json:"coin,omitempty"`
	Pond             *uint32         `protobuf:"varint,7,req,name=pond" json:"pond,omitempty"`
	Data             []*FreeRoomOver `protobuf:"bytes,8,rep,name=data" json:"data,omitempty"`
	List             []*RoomScore    `protobuf:"bytes,9,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *SFreeGameover) Reset()                    { *m = SFreeGameover{} }
func (m *SFreeGameover) String() string            { return proto.CompactTextString(m) }
func (*SFreeGameover) ProtoMessage()               {}
func (*SFreeGameover) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{39} }

const Default_SFreeGameover_Code uint32 = 4050

func (m *SFreeGameover) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeGameover_Code
}

func (m *SFreeGameover) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SFreeGameover) GetDealer() string {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return ""
}

func (m *SFreeGameover) GetDealerNum() uint32 {
	if m != nil && m.DealerNum != nil {
		return *m.DealerNum
	}
	return 0
}

func (m *SFreeGameover) GetLeftDealerNum() uint32 {
	if m != nil && m.LeftDealerNum != nil {
		return *m.LeftDealerNum
	}
	return 0
}

func (m *SFreeGameover) GetCoin() uint32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *SFreeGameover) GetPond() uint32 {
	if m != nil && m.Pond != nil {
		return *m.Pond
	}
	return 0
}

func (m *SFreeGameover) GetData() []*FreeRoomOver {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SFreeGameover) GetList() []*RoomScore {
	if m != nil {
		return m.List
	}
	return nil
}

// 百人牛牛趋势
type CFreeTrend struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4051" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFreeTrend) Reset()                    { *m = CFreeTrend{} }
func (m *CFreeTrend) String() string            { return proto.CompactTextString(m) }
func (*CFreeTrend) ProtoMessage()               {}
func (*CFreeTrend) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{40} }

const Default_CFreeTrend_Code uint32 = 4051

func (m *CFreeTrend) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CFreeTrend_Code
}

// 百人牛牛趋势
type SFreeTrend struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=4051" json:"code,omitempty"`
	List             []*FreeTrendList `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SFreeTrend) Reset()                    { *m = SFreeTrend{} }
func (m *SFreeTrend) String() string            { return proto.CompactTextString(m) }
func (*SFreeTrend) ProtoMessage()               {}
func (*SFreeTrend) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{41} }

const Default_SFreeTrend_Code uint32 = 4051

func (m *SFreeTrend) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFreeTrend_Code
}

func (m *SFreeTrend) GetList() []*FreeTrendList {
	if m != nil {
		return m.List
	}
	return nil
}

// 进入房间
type CEnterClassicRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4060" json:"code,omitempty"`
	Id               *string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CEnterClassicRoom) Reset()                    { *m = CEnterClassicRoom{} }
func (m *CEnterClassicRoom) String() string            { return proto.CompactTextString(m) }
func (*CEnterClassicRoom) ProtoMessage()               {}
func (*CEnterClassicRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{42} }

const Default_CEnterClassicRoom_Code uint32 = 4060

func (m *CEnterClassicRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CEnterClassicRoom_Code
}

func (m *CEnterClassicRoom) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type SEnterClassicRoom struct {
	Code             *uint32     `protobuf:"varint,1,opt,name=code,def=4060" json:"code,omitempty"`
	Roominfo         *RoomData   `protobuf:"bytes,2,opt,name=roominfo" json:"roominfo,omitempty"`
	Userinfo         []*RoomUser `protobuf:"bytes,3,rep,name=userinfo" json:"userinfo,omitempty"`
	Betsinfo         []*RoomBets `protobuf:"bytes,4,rep,name=betsinfo" json:"betsinfo,omitempty"`
	Error            *uint32     `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SEnterClassicRoom) Reset()                    { *m = SEnterClassicRoom{} }
func (m *SEnterClassicRoom) String() string            { return proto.CompactTextString(m) }
func (*SEnterClassicRoom) ProtoMessage()               {}
func (*SEnterClassicRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{43} }

const Default_SEnterClassicRoom_Code uint32 = 4060
const Default_SEnterClassicRoom_Error uint32 = 0

func (m *SEnterClassicRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SEnterClassicRoom_Code
}

func (m *SEnterClassicRoom) GetRoominfo() *RoomData {
	if m != nil {
		return m.Roominfo
	}
	return nil
}

func (m *SEnterClassicRoom) GetUserinfo() []*RoomUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SEnterClassicRoom) GetBetsinfo() []*RoomBets {
	if m != nil {
		return m.Betsinfo
	}
	return nil
}

func (m *SEnterClassicRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SEnterClassicRoom_Error
}

// 结算广播接口，游戏结束
type SClassicGameover struct {
	Code             *uint32        `protobuf:"varint,1,opt,name=code,def=4062" json:"code,omitempty"`
	State            *uint32        `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	Dealer           *uint32        `protobuf:"varint,3,opt,name=dealer" json:"dealer,omitempty"`
	Data             []*ClassicOver `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SClassicGameover) Reset()                    { *m = SClassicGameover{} }
func (m *SClassicGameover) String() string            { return proto.CompactTextString(m) }
func (*SClassicGameover) ProtoMessage()               {}
func (*SClassicGameover) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{44} }

const Default_SClassicGameover_Code uint32 = 4062

func (m *SClassicGameover) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SClassicGameover_Code
}

func (m *SClassicGameover) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SClassicGameover) GetDealer() uint32 {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return 0
}

func (m *SClassicGameover) GetData() []*ClassicOver {
	if m != nil {
		return m.Data
	}
	return nil
}

// 发牌
type SPubDraw struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4080" json:"code,omitempty"`
	State            *uint32 `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Card             *uint32 `protobuf:"varint,3,req,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPubDraw) Reset()                    { *m = SPubDraw{} }
func (m *SPubDraw) String() string            { return proto.CompactTextString(m) }
func (*SPubDraw) ProtoMessage()               {}
func (*SPubDraw) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{45} }

const Default_SPubDraw_Code uint32 = 4080

func (m *SPubDraw) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPubDraw_Code
}

func (m *SPubDraw) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SPubDraw) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

// 领取刮牌奖励
type CGetPrize struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4081" json:"code,omitempty"`
	Card             *uint32 `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetPrize) Reset()                    { *m = CGetPrize{} }
func (m *CGetPrize) String() string            { return proto.CompactTextString(m) }
func (*CGetPrize) ProtoMessage()               {}
func (*CGetPrize) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{46} }

const Default_CGetPrize_Code uint32 = 4081

func (m *CGetPrize) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CGetPrize_Code
}

func (m *CGetPrize) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

// 刮牌奖励,需要推送豆子和钻石的改变
type SGetPrize struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4081" json:"code,omitempty"`
	Card             *uint32 `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetPrize) Reset()                    { *m = SGetPrize{} }
func (m *SGetPrize) String() string            { return proto.CompactTextString(m) }
func (*SGetPrize) ProtoMessage()               {}
func (*SGetPrize) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{47} }

const Default_SGetPrize_Code uint32 = 4081
const Default_SGetPrize_Error uint32 = 0

func (m *SGetPrize) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGetPrize_Code
}

func (m *SGetPrize) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SGetPrize) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SGetPrize_Error
}

// 刮奖
type CPrizeCards struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4082" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPrizeCards) Reset()                    { *m = CPrizeCards{} }
func (m *CPrizeCards) String() string            { return proto.CompactTextString(m) }
func (*CPrizeCards) ProtoMessage()               {}
func (*CPrizeCards) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{48} }

const Default_CPrizeCards_Code uint32 = 4082

func (m *CPrizeCards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPrizeCards_Code
}

// 刮奖
type SPrizeCards struct {
	Code             *uint32      `protobuf:"varint,1,opt,name=code,def=4082" json:"code,omitempty"`
	List             []*PrizeCard `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32      `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SPrizeCards) Reset()                    { *m = SPrizeCards{} }
func (m *SPrizeCards) String() string            { return proto.CompactTextString(m) }
func (*SPrizeCards) ProtoMessage()               {}
func (*SPrizeCards) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{49} }

const Default_SPrizeCards_Code uint32 = 4082
const Default_SPrizeCards_Error uint32 = 0

func (m *SPrizeCards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPrizeCards_Code
}

func (m *SPrizeCards) GetList() []*PrizeCard {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SPrizeCards) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPrizeCards_Error
}

// 进入房间
type CEnterZiRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4100" json:"code,omitempty"`
	Invitecode       *string `protobuf:"bytes,2,req,name=invitecode" json:"invitecode,omitempty"`
	Id               *string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CEnterZiRoom) Reset()                    { *m = CEnterZiRoom{} }
func (m *CEnterZiRoom) String() string            { return proto.CompactTextString(m) }
func (*CEnterZiRoom) ProtoMessage()               {}
func (*CEnterZiRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{50} }

const Default_CEnterZiRoom_Code uint32 = 4100

func (m *CEnterZiRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CEnterZiRoom_Code
}

func (m *CEnterZiRoom) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *CEnterZiRoom) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type SEnterZiRoom struct {
	Code             *uint32     `protobuf:"varint,1,opt,name=code,def=4100" json:"code,omitempty"`
	Roominfo         *RoomData   `protobuf:"bytes,2,req,name=roominfo" json:"roominfo,omitempty"`
	Userinfo         []*RoomUser `protobuf:"bytes,3,rep,name=userinfo" json:"userinfo,omitempty"`
	Voteinfo         *RoomVote   `protobuf:"bytes,4,opt,name=voteinfo" json:"voteinfo,omitempty"`
	Cardinfo         []*RoomCard `protobuf:"bytes,5,rep,name=cardinfo" json:"cardinfo,omitempty"`
	Error            *uint32     `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SEnterZiRoom) Reset()                    { *m = SEnterZiRoom{} }
func (m *SEnterZiRoom) String() string            { return proto.CompactTextString(m) }
func (*SEnterZiRoom) ProtoMessage()               {}
func (*SEnterZiRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{51} }

const Default_SEnterZiRoom_Code uint32 = 4100
const Default_SEnterZiRoom_Error uint32 = 0

func (m *SEnterZiRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SEnterZiRoom_Code
}

func (m *SEnterZiRoom) GetRoominfo() *RoomData {
	if m != nil {
		return m.Roominfo
	}
	return nil
}

func (m *SEnterZiRoom) GetUserinfo() []*RoomUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *SEnterZiRoom) GetVoteinfo() *RoomVote {
	if m != nil {
		return m.Voteinfo
	}
	return nil
}

func (m *SEnterZiRoom) GetCardinfo() []*RoomCard {
	if m != nil {
		return m.Cardinfo
	}
	return nil
}

func (m *SEnterZiRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SEnterZiRoom_Error
}

// 创建房间
type CCreateZiRoom struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4101" json:"code,omitempty"`
	Rname            *string `protobuf:"bytes,2,req,name=rname" json:"rname,omitempty"`
	Rtype            *uint32 `protobuf:"varint,3,req,name=rtype" json:"rtype,omitempty"`
	Ante             *uint32 `protobuf:"varint,4,req,name=ante" json:"ante,omitempty"`
	Round            *uint32 `protobuf:"varint,5,req,name=round" json:"round,omitempty"`
	Payment          *uint32 `protobuf:"varint,6,req,name=payment" json:"payment,omitempty"`
	Count            *uint32 `protobuf:"varint,7,req,name=count" json:"count,omitempty"`
	Chat             *uint32 `protobuf:"varint,8,opt,name=chat" json:"chat,omitempty"`
	Xi               *uint32 `protobuf:"varint,9,opt,name=xi" json:"xi,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCreateZiRoom) Reset()                    { *m = CCreateZiRoom{} }
func (m *CCreateZiRoom) String() string            { return proto.CompactTextString(m) }
func (*CCreateZiRoom) ProtoMessage()               {}
func (*CCreateZiRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{52} }

const Default_CCreateZiRoom_Code uint32 = 4101

func (m *CCreateZiRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CCreateZiRoom_Code
}

func (m *CCreateZiRoom) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

func (m *CCreateZiRoom) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *CCreateZiRoom) GetAnte() uint32 {
	if m != nil && m.Ante != nil {
		return *m.Ante
	}
	return 0
}

func (m *CCreateZiRoom) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *CCreateZiRoom) GetPayment() uint32 {
	if m != nil && m.Payment != nil {
		return *m.Payment
	}
	return 0
}

func (m *CCreateZiRoom) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *CCreateZiRoom) GetChat() uint32 {
	if m != nil && m.Chat != nil {
		return *m.Chat
	}
	return 0
}

func (m *CCreateZiRoom) GetXi() uint32 {
	if m != nil && m.Xi != nil {
		return *m.Xi
	}
	return 0
}

// 返回房间数据,
type SCreateZiRoom struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=4101" json:"code,omitempty"`
	Rdata            *RoomData `protobuf:"bytes,2,opt,name=rdata" json:"rdata,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCreateZiRoom) Reset()                    { *m = SCreateZiRoom{} }
func (m *SCreateZiRoom) String() string            { return proto.CompactTextString(m) }
func (*SCreateZiRoom) ProtoMessage()               {}
func (*SCreateZiRoom) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{53} }

const Default_SCreateZiRoom_Code uint32 = 4101
const Default_SCreateZiRoom_Error uint32 = 0

func (m *SCreateZiRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SCreateZiRoom_Code
}

func (m *SCreateZiRoom) GetRdata() *RoomData {
	if m != nil {
		return m.Rdata
	}
	return nil
}

func (m *SCreateZiRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SCreateZiRoom_Error
}

// 其他玩家进入房间
type SZiCamein struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=4104" json:"code,omitempty"`
	Userinfo         *RoomUser `protobuf:"bytes,2,opt,name=userinfo" json:"userinfo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SZiCamein) Reset()                    { *m = SZiCamein{} }
func (m *SZiCamein) String() string            { return proto.CompactTextString(m) }
func (*SZiCamein) ProtoMessage()               {}
func (*SZiCamein) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{54} }

const Default_SZiCamein_Code uint32 = 4104

func (m *SZiCamein) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SZiCamein_Code
}

func (m *SZiCamein) GetUserinfo() *RoomUser {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

// 结算广播接口，游戏结束
type SZiGameover struct {
	Code             *uint32       `protobuf:"varint,1,opt,name=code,def=4102" json:"code,omitempty"`
	Dealer           *uint32       `protobuf:"varint,2,opt,name=dealer" json:"dealer,omitempty"`
	Seat             *uint32       `protobuf:"varint,3,opt,name=seat" json:"seat,omitempty"`
	Value            *uint32       `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	Round            *uint32       `protobuf:"varint,5,opt,name=round" json:"round,omitempty"`
	Xi               *uint32       `protobuf:"varint,6,opt,name=xi" json:"xi,omitempty"`
	Fan              *uint32       `protobuf:"varint,7,opt,name=fan" json:"fan,omitempty"`
	Deng             *uint32       `protobuf:"varint,8,opt,name=deng" json:"deng,omitempty"`
	Seats            []*RoomSeat   `protobuf:"bytes,9,rep,name=seats" json:"seats,omitempty"`
	Cards            []*RoomCard   `protobuf:"bytes,10,rep,name=cards" json:"cards,omitempty"`
	List             []*ZiRoomOver `protobuf:"bytes,11,rep,name=list" json:"list,omitempty"`
	Lastcards        []uint32      `protobuf:"varint,12,rep,name=lastcards" json:"lastcards,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SZiGameover) Reset()                    { *m = SZiGameover{} }
func (m *SZiGameover) String() string            { return proto.CompactTextString(m) }
func (*SZiGameover) ProtoMessage()               {}
func (*SZiGameover) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{55} }

const Default_SZiGameover_Code uint32 = 4102

func (m *SZiGameover) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SZiGameover_Code
}

func (m *SZiGameover) GetDealer() uint32 {
	if m != nil && m.Dealer != nil {
		return *m.Dealer
	}
	return 0
}

func (m *SZiGameover) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SZiGameover) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SZiGameover) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *SZiGameover) GetXi() uint32 {
	if m != nil && m.Xi != nil {
		return *m.Xi
	}
	return 0
}

func (m *SZiGameover) GetFan() uint32 {
	if m != nil && m.Fan != nil {
		return *m.Fan
	}
	return 0
}

func (m *SZiGameover) GetDeng() uint32 {
	if m != nil && m.Deng != nil {
		return *m.Deng
	}
	return 0
}

func (m *SZiGameover) GetSeats() []*RoomSeat {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *SZiGameover) GetCards() []*RoomCard {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SZiGameover) GetList() []*ZiRoomOver {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SZiGameover) GetLastcards() []uint32 {
	if m != nil {
		return m.Lastcards
	}
	return nil
}

// 个人牌局记录,默认最近30场
type CZiGameRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4103" json:"code,omitempty"`
	Page             *uint32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CZiGameRecord) Reset()                    { *m = CZiGameRecord{} }
func (m *CZiGameRecord) String() string            { return proto.CompactTextString(m) }
func (*CZiGameRecord) ProtoMessage()               {}
func (*CZiGameRecord) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{56} }

const Default_CZiGameRecord_Code uint32 = 4103

func (m *CZiGameRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CZiGameRecord_Code
}

func (m *CZiGameRecord) GetPage() uint32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

type SZiGameRecord struct {
	Code             *uint32         `protobuf:"varint,1,opt,name=code,def=4103" json:"code,omitempty"`
	List             []*ZiRecordList `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *SZiGameRecord) Reset()                    { *m = SZiGameRecord{} }
func (m *SZiGameRecord) String() string            { return proto.CompactTextString(m) }
func (*SZiGameRecord) ProtoMessage()               {}
func (*SZiGameRecord) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{57} }

const Default_SZiGameRecord_Code uint32 = 4103

func (m *SZiGameRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SZiGameRecord_Code
}

func (m *SZiGameRecord) GetList() []*ZiRecordList {
	if m != nil {
		return m.List
	}
	return nil
}

// 发牌
type SPushDeal struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4109" json:"code,omitempty"`
	Seat             *uint32  `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Cards            []uint32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SPushDeal) Reset()                    { *m = SPushDeal{} }
func (m *SPushDeal) String() string            { return proto.CompactTextString(m) }
func (*SPushDeal) ProtoMessage()               {}
func (*SPushDeal) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{58} }

const Default_SPushDeal_Code uint32 = 4109

func (m *SPushDeal) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushDeal_Code
}

func (m *SPushDeal) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPushDeal) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 庄家发牌
type SPushDealerDeal struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4110" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Card             *uint32 `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	Value            *uint32 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPushDealerDeal) Reset()                    { *m = SPushDealerDeal{} }
func (m *SPushDealerDeal) String() string            { return proto.CompactTextString(m) }
func (*SPushDealerDeal) ProtoMessage()               {}
func (*SPushDealerDeal) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{59} }

const Default_SPushDealerDeal_Code uint32 = 4110

func (m *SPushDealerDeal) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushDealerDeal_Code
}

func (m *SPushDealerDeal) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPushDealerDeal) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SPushDealerDeal) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// 摸牌
type SPushDraw struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4105" json:"code,omitempty"`
	Seat             *uint32  `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Card             *uint32  `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	Value            *uint32  `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	Count            *uint32  `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Cards            []uint32 `protobuf:"varint,6,rep,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SPushDraw) Reset()                    { *m = SPushDraw{} }
func (m *SPushDraw) String() string            { return proto.CompactTextString(m) }
func (*SPushDraw) ProtoMessage()               {}
func (*SPushDraw) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{60} }

const Default_SPushDraw_Code uint32 = 4105

func (m *SPushDraw) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushDraw_Code
}

func (m *SPushDraw) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPushDraw) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SPushDraw) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SPushDraw) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *SPushDraw) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 打牌
type CPushDiscard struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4106" json:"code,omitempty"`
	Card             *uint32 `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPushDiscard) Reset()                    { *m = CPushDiscard{} }
func (m *CPushDiscard) String() string            { return proto.CompactTextString(m) }
func (*CPushDiscard) ProtoMessage()               {}
func (*CPushDiscard) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{61} }

const Default_CPushDiscard_Code uint32 = 4106

func (m *CPushDiscard) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPushDiscard_Code
}

func (m *CPushDiscard) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

// 打牌
type SPushDiscard struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4106" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Card             *uint32 `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	Value            *uint32 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPushDiscard) Reset()                    { *m = SPushDiscard{} }
func (m *SPushDiscard) String() string            { return proto.CompactTextString(m) }
func (*SPushDiscard) ProtoMessage()               {}
func (*SPushDiscard) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{62} }

const Default_SPushDiscard_Code uint32 = 4106
const Default_SPushDiscard_Error uint32 = 0

func (m *SPushDiscard) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushDiscard_Code
}

func (m *SPushDiscard) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPushDiscard) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SPushDiscard) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SPushDiscard) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPushDiscard_Error
}

// 自动操作(提,跑,偎)
type SPushAuto struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4107" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Card             *uint32 `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	Value            *uint32 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPushAuto) Reset()                    { *m = SPushAuto{} }
func (m *SPushAuto) String() string            { return proto.CompactTextString(m) }
func (*SPushAuto) ProtoMessage()               {}
func (*SPushAuto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{63} }

const Default_SPushAuto_Code uint32 = 4107

func (m *SPushAuto) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushAuto_Code
}

func (m *SPushAuto) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPushAuto) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SPushAuto) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// 玩家吃,碰,胡操作
type COperate struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4108" json:"code,omitempty"`
	Value            *uint32  `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	Cards            []uint32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
	Bione            []uint32 `protobuf:"varint,4,rep,name=bione" json:"bione,omitempty"`
	Bitwo            []uint32 `protobuf:"varint,5,rep,name=bitwo" json:"bitwo,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *COperate) Reset()                    { *m = COperate{} }
func (m *COperate) String() string            { return proto.CompactTextString(m) }
func (*COperate) ProtoMessage()               {}
func (*COperate) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{64} }

const Default_COperate_Code uint32 = 4108

func (m *COperate) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_COperate_Code
}

func (m *COperate) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *COperate) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *COperate) GetBione() []uint32 {
	if m != nil {
		return m.Bione
	}
	return nil
}

func (m *COperate) GetBitwo() []uint32 {
	if m != nil {
		return m.Bitwo
	}
	return nil
}

type SOperate struct {
	Code             *uint32  `protobuf:"varint,1,opt,name=code,def=4108" json:"code,omitempty"`
	Seat             *uint32  `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Beseat           *uint32  `protobuf:"varint,3,opt,name=beseat" json:"beseat,omitempty"`
	Card             *uint32  `protobuf:"varint,4,opt,name=card" json:"card,omitempty"`
	Value            *uint32  `protobuf:"varint,5,opt,name=value" json:"value,omitempty"`
	Cards            []uint32 `protobuf:"varint,6,rep,name=cards" json:"cards,omitempty"`
	Bione            []uint32 `protobuf:"varint,7,rep,name=bione" json:"bione,omitempty"`
	Bitwo            []uint32 `protobuf:"varint,8,rep,name=bitwo" json:"bitwo,omitempty"`
	Error            *uint32  `protobuf:"varint,9,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SOperate) Reset()                    { *m = SOperate{} }
func (m *SOperate) String() string            { return proto.CompactTextString(m) }
func (*SOperate) ProtoMessage()               {}
func (*SOperate) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{65} }

const Default_SOperate_Code uint32 = 4108
const Default_SOperate_Error uint32 = 0

func (m *SOperate) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOperate_Code
}

func (m *SOperate) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SOperate) GetBeseat() uint32 {
	if m != nil && m.Beseat != nil {
		return *m.Beseat
	}
	return 0
}

func (m *SOperate) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *SOperate) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *SOperate) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SOperate) GetBione() []uint32 {
	if m != nil {
		return m.Bione
	}
	return nil
}

func (m *SOperate) GetBitwo() []uint32 {
	if m != nil {
		return m.Bitwo
	}
	return nil
}

func (m *SOperate) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SOperate_Error
}

// 房间状态
type SPushStatus struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4111" json:"code,omitempty"`
	Seat             *uint32 `protobuf:"varint,2,opt,name=seat" json:"seat,omitempty"`
	Status           *int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPushStatus) Reset()                    { *m = SPushStatus{} }
func (m *SPushStatus) String() string            { return proto.CompactTextString(m) }
func (*SPushStatus) ProtoMessage()               {}
func (*SPushStatus) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{66} }

const Default_SPushStatus_Code uint32 = 4111

func (m *SPushStatus) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPushStatus_Code
}

func (m *SPushStatus) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *SPushStatus) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*CEnterRoom)(nil), "protocol.CEnterRoom")
	proto.RegisterType((*SEnterRoom)(nil), "protocol.SEnterRoom")
	proto.RegisterType((*CCreateRoom)(nil), "protocol.CCreateRoom")
	proto.RegisterType((*SCreateRoom)(nil), "protocol.SCreateRoom")
	proto.RegisterType((*SCamein)(nil), "protocol.SCamein")
	proto.RegisterType((*CLeave)(nil), "protocol.CLeave")
	proto.RegisterType((*SLeave)(nil), "protocol.SLeave")
	proto.RegisterType((*CKick)(nil), "protocol.CKick")
	proto.RegisterType((*SKick)(nil), "protocol.SKick")
	proto.RegisterType((*CReady)(nil), "protocol.CReady")
	proto.RegisterType((*SReady)(nil), "protocol.SReady")
	proto.RegisterType((*SDraw)(nil), "protocol.SDraw")
	proto.RegisterType((*CDealer)(nil), "protocol.CDealer")
	proto.RegisterType((*SDealer)(nil), "protocol.SDealer")
	proto.RegisterType((*SPushDealer)(nil), "protocol.SPushDealer")
	proto.RegisterType((*CBet)(nil), "protocol.CBet")
	proto.RegisterType((*SBet)(nil), "protocol.SBet")
	proto.RegisterType((*CNiu)(nil), "protocol.CNiu")
	proto.RegisterType((*SNiu)(nil), "protocol.SNiu")
	proto.RegisterType((*SGameover)(nil), "protocol.SGameover")
	proto.RegisterType((*CLaunchVote)(nil), "protocol.CLaunchVote")
	proto.RegisterType((*SLaunchVote)(nil), "protocol.SLaunchVote")
	proto.RegisterType((*CVote)(nil), "protocol.CVote")
	proto.RegisterType((*SVote)(nil), "protocol.SVote")
	proto.RegisterType((*SVoteResult)(nil), "protocol.SVoteResult")
	proto.RegisterType((*CGameRecord)(nil), "protocol.CGameRecord")
	proto.RegisterType((*SGameRecord)(nil), "protocol.SGameRecord")
	proto.RegisterType((*CEnterFreeRoom)(nil), "protocol.CEnterFreeRoom")
	proto.RegisterType((*SEnterFreeRoom)(nil), "protocol.SEnterFreeRoom")
	proto.RegisterType((*SFreeCamein)(nil), "protocol.SFreeCamein")
	proto.RegisterType((*CFreeDealer)(nil), "protocol.CFreeDealer")
	proto.RegisterType((*SFreeDealer)(nil), "protocol.SFreeDealer")
	proto.RegisterType((*CDealerList)(nil), "protocol.CDealerList")
	proto.RegisterType((*SDealerList)(nil), "protocol.SDealerList")
	proto.RegisterType((*CFreeSit)(nil), "protocol.CFreeSit")
	proto.RegisterType((*SFreeSit)(nil), "protocol.SFreeSit")
	proto.RegisterType((*CFreeBet)(nil), "protocol.CFreeBet")
	proto.RegisterType((*SFreeBet)(nil), "protocol.SFreeBet")
	proto.RegisterType((*SFreeGamestart)(nil), "protocol.SFreeGamestart")
	proto.RegisterType((*SFreeGameover)(nil), "protocol.SFreeGameover")
	proto.RegisterType((*CFreeTrend)(nil), "protocol.CFreeTrend")
	proto.RegisterType((*SFreeTrend)(nil), "protocol.SFreeTrend")
	proto.RegisterType((*CEnterClassicRoom)(nil), "protocol.CEnterClassicRoom")
	proto.RegisterType((*SEnterClassicRoom)(nil), "protocol.SEnterClassicRoom")
	proto.RegisterType((*SClassicGameover)(nil), "protocol.SClassicGameover")
	proto.RegisterType((*SPubDraw)(nil), "protocol.SPubDraw")
	proto.RegisterType((*CGetPrize)(nil), "protocol.CGetPrize")
	proto.RegisterType((*SGetPrize)(nil), "protocol.SGetPrize")
	proto.RegisterType((*CPrizeCards)(nil), "protocol.CPrizeCards")
	proto.RegisterType((*SPrizeCards)(nil), "protocol.SPrizeCards")
	proto.RegisterType((*CEnterZiRoom)(nil), "protocol.CEnterZiRoom")
	proto.RegisterType((*SEnterZiRoom)(nil), "protocol.SEnterZiRoom")
	proto.RegisterType((*CCreateZiRoom)(nil), "protocol.CCreateZiRoom")
	proto.RegisterType((*SCreateZiRoom)(nil), "protocol.SCreateZiRoom")
	proto.RegisterType((*SZiCamein)(nil), "protocol.SZiCamein")
	proto.RegisterType((*SZiGameover)(nil), "protocol.SZiGameover")
	proto.RegisterType((*CZiGameRecord)(nil), "protocol.CZiGameRecord")
	proto.RegisterType((*SZiGameRecord)(nil), "protocol.SZiGameRecord")
	proto.RegisterType((*SPushDeal)(nil), "protocol.SPushDeal")
	proto.RegisterType((*SPushDealerDeal)(nil), "protocol.SPushDealerDeal")
	proto.RegisterType((*SPushDraw)(nil), "protocol.SPushDraw")
	proto.RegisterType((*CPushDiscard)(nil), "protocol.CPushDiscard")
	proto.RegisterType((*SPushDiscard)(nil), "protocol.SPushDiscard")
	proto.RegisterType((*SPushAuto)(nil), "protocol.SPushAuto")
	proto.RegisterType((*COperate)(nil), "protocol.COperate")
	proto.RegisterType((*SOperate)(nil), "protocol.SOperate")
	proto.RegisterType((*SPushStatus)(nil), "protocol.SPushStatus")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 1804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x19, 0xcd, 0x8f, 0xdb, 0xc4,
	0x57, 0x4e, 0x9c, 0x6c, 0x32, 0xdb, 0xed, 0xaf, 0xcd, 0xaf, 0xbf, 0x76, 0x55, 0xfd, 0x84, 0x2a,
	0x0b, 0xb5, 0x4b, 0x91, 0x56, 0xc9, 0x92, 0xdd, 0xa6, 0x7c, 0x08, 0x81, 0x97, 0xf6, 0xc0, 0xd2,
	0x16, 0x9b, 0x02, 0xea, 0x05, 0x79, 0x13, 0xb7, 0x6b, 0xc8, 0xda, 0x91, 0xed, 0x6c, 0xd9, 0x8a,
	0x0f, 0x71, 0xe0, 0xcc, 0x95, 0x3b, 0xff, 0x03, 0x57, 0xc4, 0x01, 0xee, 0x08, 0xc1, 0xbf, 0x03,
	0xef, 0xbd, 0x19, 0x8f, 0x9d, 0x78, 0x26, 0xf1, 0x2e, 0x8b, 0xd4, 0x53, 0x66, 0xc6, 0x6f, 0xde,
	0xf7, 0xbc, 0xaf, 0x30, 0x16, 0x47, 0xd1, 0xe1, 0xe6, 0x24, 0x8e, 0xd2, 0xa8, 0xd3, 0xa2, 0x9f,
	0x61, 0x34, 0xbe, 0xda, 0x3a, 0x8a, 0xf8, 0x99, 0x75, 0x87, 0x31, 0xfb, 0x9d, 0x30, 0xf5, 0x63,
	0x07, 0xe0, 0x3a, 0xeb, 0xcc, 0x1c, 0x46, 0x23, 0x7f, 0xdd, 0xb8, 0x66, 0x6c, 0xac, 0xbd, 0x6a,
	0xf6, 0xbb, 0xdd, 0xae, 0x43, 0x27, 0x9d, 0x17, 0x18, 0x0b, 0xc2, 0xa3, 0x20, 0xf5, 0xe9, 0x7b,
	0xed, 0x5a, 0x6d, 0xa3, 0xed, 0x14, 0x4e, 0xac, 0xbf, 0x0c, 0xc6, 0xdc, 0x2a, 0x88, 0x36, 0x59,
	0x0b, 0x59, 0x0a, 0xc2, 0xc7, 0x11, 0xa1, 0x59, 0xdd, 0xea, 0x6c, 0x66, 0x7c, 0x6d, 0xe2, 0xdd,
	0x5d, 0x2f, 0xf5, 0x1c, 0x09, 0x83, 0xf0, 0xd3, 0xc4, 0x8f, 0x09, 0xbe, 0x7e, 0xad, 0x5e, 0x86,
	0x7f, 0x08, 0x5f, 0x1d, 0x09, 0x83, 0xf0, 0x47, 0x51, 0xea, 0x13, 0xbc, 0x09, 0xd4, 0x4b, 0xf0,
	0x1f, 0xc2, 0x57, 0x47, 0xc2, 0x20, 0xfc, 0xbe, 0x9f, 0x26, 0x04, 0xdf, 0x50, 0xe1, 0x7f, 0x1b,
	0xbe, 0x3a, 0x12, 0xa6, 0x73, 0x85, 0x35, 0xfc, 0x38, 0x8e, 0xe2, 0xf5, 0x26, 0x89, 0x66, 0x74,
	0x1d, 0xbe, 0xb7, 0x7e, 0x36, 0xd8, 0xaa, 0x6d, 0xc7, 0xbe, 0x07, 0xe8, 0xd5, 0x2a, 0xe8, 0x09,
	0x15, 0x5c, 0x62, 0x8d, 0x38, 0xf4, 0x0e, 0x33, 0x35, 0xf2, 0x0d, 0x9d, 0xa6, 0xc7, 0x13, 0x1f,
	0xa4, 0xac, 0x6d, 0xac, 0x39, 0x7c, 0xd3, 0xe9, 0x30, 0xd3, 0x03, 0xad, 0x82, 0x28, 0x78, 0x48,
	0x6b, 0x82, 0x8c, 0xa6, 0xe1, 0x08, 0xf8, 0xe5, 0x90, 0xb8, 0x01, 0x7a, 0x2b, 0x13, 0xef, 0xf8,
	0xd0, 0x0f, 0x53, 0x60, 0x0d, 0xcf, 0xb3, 0x2d, 0xc2, 0x0f, 0x01, 0x24, 0x5d, 0x5f, 0xe1, 0xf0,
	0xb4, 0x41, 0xcc, 0xc3, 0x03, 0x2f, 0x5d, 0x6f, 0x21, 0x7f, 0x0e, 0xad, 0xad, 0x4f, 0xd9, 0xaa,
	0x5b, 0x49, 0x84, 0x0d, 0x60, 0x61, 0x04, 0x86, 0x02, 0x11, 0x0c, 0x8d, 0x09, 0x39, 0x40, 0xae,
	0xaf, 0xfa, 0x9c, 0xbe, 0x5c, 0xb6, 0xe2, 0xda, 0x20, 0x78, 0x10, 0x2a, 0xe8, 0xbc, 0x92, 0x7b,
	0x8b, 0xb4, 0xbe, 0xd2, 0x5b, 0x66, 0xad, 0x6f, 0x59, 0xac, 0x69, 0xef, 0xf9, 0xde, 0x91, 0xaf,
	0xc0, 0xd9, 0xe7, 0x38, 0xad, 0x27, 0xac, 0xe9, 0x2e, 0x81, 0x41, 0xe5, 0x24, 0xa0, 0x06, 0x12,
	0x0f, 0x94, 0x83, 0xeb, 0xce, 0x65, 0xd6, 0x24, 0x3a, 0x23, 0x12, 0xa5, 0xed, 0x88, 0x5d, 0x2e,
	0xa1, 0x39, 0x27, 0xe1, 0x36, 0x6b, 0xd8, 0xef, 0x06, 0xc3, 0xcf, 0x14, 0x74, 0xb6, 0x4b, 0x74,
	0x6a, 0x19, 0x1d, 0xeb, 0x2b, 0xd6, 0x70, 0x2b, 0x5f, 0x5b, 0xce, 0x1e, 0x9c, 0xc7, 0x7e, 0x32,
	0x1d, 0xa7, 0x9c, 0x3f, 0x47, 0xec, 0x72, 0xb6, 0x1b, 0x73, 0x6c, 0x0f, 0x40, 0x87, 0x8e, 0xef,
	0x8d, 0x8e, 0x15, 0x0c, 0xec, 0x14, 0x5c, 0x18, 0x41, 0x88, 0xf1, 0x96, 0xc3, 0x37, 0x96, 0x0f,
	0x9a, 0x5d, 0x76, 0x53, 0xc5, 0xba, 0xc4, 0x86, 0x9c, 0x67, 0xd8, 0xf4, 0x7a, 0xf5, 0x40, 0x41,
	0xbb, 0xb1, 0xf7, 0x54, 0x41, 0xe5, 0x96, 0x5e, 0xaf, 0x48, 0x25, 0x49, 0xc1, 0xb5, 0xb3, 0x07,
	0x46, 0x1b, 0x7a, 0x1c, 0x5e, 0x3c, 0x4a, 0x80, 0x4a, 0x9d, 0x1e, 0x07, 0x6e, 0xac, 0xf7, 0xd8,
	0x8a, 0xbd, 0xeb, 0x7b, 0x63, 0x3f, 0x56, 0x10, 0x19, 0x08, 0x22, 0xa0, 0xd9, 0x11, 0xc1, 0x08,
	0x2d, 0x88, 0x5d, 0xe7, 0x02, 0xab, 0x87, 0xd3, 0x43, 0xee, 0xf0, 0x0e, 0x2e, 0xad, 0x67, 0xe0,
	0xeb, 0x4b, 0xd1, 0xa9, 0x78, 0xce, 0x49, 0xd4, 0x55, 0x24, 0x4c, 0x49, 0x42, 0x6f, 0xce, 0x37,
	0xe1, 0x4d, 0x3f, 0x98, 0x26, 0x07, 0x5a, 0xfa, 0xb7, 0x95, 0xe2, 0xac, 0x65, 0xb4, 0xac, 0x07,
	0xcc, 0xb4, 0x21, 0x08, 0x96, 0x6f, 0xf6, 0xb2, 0x98, 0x0e, 0xa1, 0x07, 0xb9, 0x85, 0x18, 0x29,
	0xcc, 0x9a, 0x6d, 0x51, 0xbb, 0x47, 0xde, 0x78, 0x2a, 0x75, 0x4e, 0x1b, 0xeb, 0x4b, 0x66, 0xba,
	0x8b, 0x31, 0xaa, 0xbc, 0xa4, 0x40, 0xa5, 0xae, 0xa1, 0x62, 0x16, 0xa8, 0xe8, 0x35, 0xb2, 0x07,
	0x02, 0xdd, 0x0b, 0xa6, 0x0a, 0xf2, 0x85, 0x08, 0xcd, 0x11, 0x72, 0xfa, 0x02, 0xa1, 0x74, 0x95,
	0x7a, 0xd1, 0x55, 0x8e, 0x41, 0x98, 0xc5, 0xd8, 0x34, 0x2e, 0x9f, 0x29, 0x46, 0x45, 0xa1, 0xe8,
	0x8c, 0x7a, 0x41, 0x7e, 0x30, 0x58, 0xdb, 0xbd, 0x0b, 0x31, 0x34, 0x3a, 0x52, 0x59, 0xb6, 0xb7,
	0xb5, 0xd8, 0xb2, 0x79, 0x22, 0xa9, 0x17, 0x13, 0xc9, 0x75, 0x66, 0x52, 0x68, 0x37, 0x55, 0xd9,
	0xf0, 0x3e, 0x50, 0x72, 0xe8, 0x3b, 0xc2, 0x8d, 0x83, 0x24, 0x2d, 0x67, 0x4d, 0x84, 0xd9, 0x83,
	0x2f, 0x0e, 0x7d, 0xb7, 0x6e, 0x40, 0x5e, 0xdc, 0xf3, 0xa6, 0xe1, 0xf0, 0x00, 0x53, 0xaf, 0x82,
	0x4d, 0x11, 0x1a, 0xac, 0xf7, 0xc1, 0x53, 0xab, 0x00, 0xea, 0x5e, 0x77, 0x21, 0xcf, 0x14, 0x43,
	0xb0, 0x06, 0x59, 0x21, 0x54, 0x60, 0x31, 0x90, 0x21, 0xc3, 0xb5, 0xf5, 0x09, 0x44, 0x98, 0x93,
	0x5f, 0x93, 0x7c, 0xd5, 0x55, 0x7c, 0x99, 0x45, 0xbe, 0x5e, 0x03, 0x51, 0xa9, 0x10, 0xe1, 0xb1,
	0xb8, 0x4c, 0x66, 0xb0, 0x80, 0x3b, 0xb8, 0x6c, 0xa3, 0xd5, 0x1d, 0x28, 0xbd, 0xe2, 0x51, 0xf9,
	0xf2, 0x56, 0xe1, 0x15, 0x4d, 0xbc, 0x27, 0xf2, 0x32, 0xae, 0x49, 0xc9, 0x95, 0x2e, 0x6f, 0x08,
	0xf3, 0xd6, 0xc8, 0xbc, 0x97, 0x0a, 0x6e, 0x40, 0x37, 0x0b, 0x06, 0xbe, 0xc9, 0xce, 0xf3, 0x1a,
	0xf2, 0x4e, 0xec, 0x6b, 0x0a, 0x87, 0xbe, 0xc0, 0x6a, 0xfd, 0x6e, 0xb0, 0xf3, 0x6e, 0x45, 0xe0,
	0xc5, 0xb5, 0x62, 0x76, 0xbf, 0x6a, 0xad, 0x88, 0xf0, 0xe5, 0x5a, 0xf1, 0x6c, 0x6a, 0xbf, 0x8f,
	0x40, 0xa9, 0x88, 0x5f, 0x57, 0xcf, 0xf4, 0x7b, 0x55, 0xea, 0x99, 0x32, 0x87, 0x68, 0x2d, 0x1b,
	0x8f, 0x75, 0xc1, 0xbb, 0xbf, 0x95, 0x47, 0x2c, 0x9e, 0xdc, 0x44, 0xc4, 0xe2, 0xc9, 0x0d, 0x6b,
	0xbc, 0x28, 0x08, 0xc5, 0x9b, 0xa0, 0xb5, 0xf5, 0xa3, 0x21, 0x98, 0x3d, 0x25, 0xce, 0xd9, 0x94,
	0xd4, 0x96, 0xc1, 0x24, 0xaf, 0x3f, 0x4c, 0x7e, 0x2e, 0xea, 0x8f, 0xab, 0xac, 0x15, 0x42, 0x35,
	0x43, 0x05, 0x6f, 0x83, 0xbe, 0xc8, 0xbd, 0xe4, 0xaf, 0x99, 0xf3, 0x97, 0x2b, 0x79, 0x65, 0x4e,
	0xc9, 0x18, 0x47, 0x38, 0xcf, 0xe8, 0x7b, 0x0a, 0xbe, 0x45, 0xd1, 0x48, 0x55, 0x6c, 0x15, 0x40,
	0xbd, 0x8b, 0xe7, 0xb7, 0xb9, 0x8b, 0xeb, 0xab, 0xd8, 0x7b, 0xac, 0x45, 0x06, 0x72, 0x03, 0x15,
	0xa1, 0x7e, 0x59, 0x93, 0x54, 0x2e, 0x49, 0xeb, 0xcc, 0x87, 0x0b, 0xeb, 0x17, 0x83, 0xb5, 0xdc,
	0x33, 0x44, 0x78, 0x2a, 0xb3, 0x00, 0xf6, 0xc9, 0x01, 0xa8, 0x82, 0x1a, 0x09, 0x68, 0x50, 0x68,
	0x23, 0x8d, 0xc5, 0xbb, 0x88, 0x39, 0x63, 0xb5, 0x34, 0x7a, 0x51, 0xa6, 0xf9, 0xfe, 0x92, 0x40,
	0xae, 0x28, 0x19, 0x7e, 0xca, 0xf4, 0x72, 0x72, 0x84, 0xa0, 0x81, 0x7d, 0xbf, 0xa0, 0x17, 0xb1,
	0xd3, 0x54, 0x0d, 0xb9, 0xbe, 0x1a, 0x33, 0xfa, 0xca, 0x5d, 0x35, 0x97, 0x1e, 0xce, 0x30, 0x36,
	0x64, 0x1a, 0xc1, 0xb5, 0x5e, 0x23, 0xbf, 0x62, 0xe4, 0x43, 0x09, 0x30, 0xfa, 0x82, 0xbd, 0x62,
	0x95, 0x1c, 0x03, 0x95, 0x7d, 0x97, 0x3e, 0xbd, 0x8c, 0x37, 0xb3, 0xc0, 0x9b, 0xb4, 0x61, 0xa3,
	0x68, 0xc3, 0xff, 0xb3, 0x36, 0xbf, 0x73, 0x0f, 0xaa, 0x47, 0x2e, 0x4a, 0x7e, 0xd0, 0x79, 0x91,
	0xad, 0x8d, 0xfd, 0xc7, 0xe9, 0xae, 0x84, 0xe0, 0x82, 0xcd, 0x1e, 0x5a, 0xdf, 0xd7, 0xd8, 0x9a,
	0x14, 0x44, 0x5d, 0x79, 0x6c, 0x77, 0x4f, 0x25, 0xc7, 0x0c, 0x77, 0xe6, 0x52, 0xee, 0x1a, 0x0a,
	0xee, 0x74, 0x76, 0x9a, 0x44, 0x50, 0xe6, 0x08, 0x3b, 0xe1, 0xba, 0x73, 0x53, 0x54, 0x39, 0x2d,
	0x7a, 0xfb, 0x97, 0xcb, 0x79, 0xa5, 0x50, 0xe9, 0xdc, 0x10, 0x71, 0xa2, 0x4d, 0xb0, 0xff, 0x9d,
	0xcd, 0x11, 0x2e, 0x64, 0x43, 0x5f, 0x64, 0xc2, 0xeb, 0x8c, 0x91, 0xd7, 0x7f, 0x10, 0xfb, 0xa1,
	0x22, 0xb7, 0x6e, 0x8b, 0x34, 0x00, 0xbd, 0x2f, 0x73, 0x2b, 0xc0, 0x75, 0x5e, 0x9e, 0x09, 0x50,
	0x57, 0x66, 0x99, 0xa4, 0xcb, 0x85, 0x34, 0xfc, 0x06, 0xbb, 0xc8, 0xd3, 0xb0, 0x3d, 0xf6, 0x92,
	0x24, 0x18, 0xaa, 0x93, 0xeb, 0x4e, 0x66, 0x9a, 0xf3, 0xac, 0x06, 0x4e, 0x5e, 0xa3, 0x5e, 0x11,
	0x56, 0xd6, 0x9f, 0x06, 0xbb, 0xe8, 0x9e, 0xe0, 0xfe, 0x6c, 0x72, 0x36, 0xfe, 0x8d, 0x41, 0x8e,
	0x4c, 0xce, 0xe6, 0x49, 0x92, 0xf3, 0x7c, 0x95, 0xfc, 0xad, 0xc1, 0x2e, 0xb8, 0x42, 0x26, 0xbd,
	0xcb, 0xee, 0x54, 0xcf, 0x7a, 0x46, 0xa1, 0x84, 0x7e, 0x69, 0xa6, 0x58, 0xfe, 0x5f, 0xce, 0xa1,
	0x20, 0x98, 0x7b, 0x11, 0x86, 0x44, 0x68, 0xc4, 0xf6, 0xd5, 0x9d, 0xeb, 0x60, 0xf1, 0x8b, 0x41,
	0xaf, 0x86, 0x5e, 0x20, 0x8b, 0xec, 0xb8, 0xb6, 0x6e, 0xb3, 0xb6, 0x7d, 0xd7, 0x4f, 0x1f, 0xc4,
	0xc1, 0x33, 0x45, 0xa1, 0x3a, 0x28, 0x74, 0x1f, 0x74, 0x55, 0x74, 0x1f, 0x74, 0xd5, 0xc1, 0xbe,
	0xe1, 0x54, 0x57, 0xf5, 0x99, 0x10, 0xd3, 0x33, 0x21, 0xb4, 0xa9, 0x69, 0x29, 0x63, 0x15, 0x0a,
	0xb6, 0x02, 0x6c, 0x48, 0x2b, 0x00, 0xca, 0x67, 0x57, 0x9b, 0x7f, 0x76, 0xf2, 0xf6, 0xb2, 0xec,
	0xfc, 0x31, 0x3b, 0xc7, 0x9f, 0xc4, 0xa3, 0x40, 0xe9, 0xcd, 0xbd, 0xaa, 0xf3, 0x4d, 0xf1, 0x5a,
	0xea, 0xf2, 0xb5, 0x7c, 0x53, 0x63, 0xe7, 0xdc, 0x6a, 0xa8, 0x9f, 0xc3, 0x89, 0x27, 0x5a, 0x52,
	0x5f, 0xf5, 0x92, 0x66, 0x25, 0x8c, 0xbe, 0xea, 0x85, 0x5a, 0x7e, 0x4d, 0x4c, 0x3c, 0xb5, 0x4a,
	0x78, 0xee, 0x67, 0x9e, 0x68, 0xd9, 0xcf, 0x03, 0x08, 0xed, 0x78, 0x02, 0x2b, 0x6b, 0x0c, 0xd9,
	0xad, 0xa2, 0x50, 0x67, 0x30, 0x05, 0x7d, 0x08, 0x2f, 0xf1, 0x51, 0xa0, 0xe9, 0x1b, 0x7a, 0x72,
	0x1e, 0x39, 0xdb, 0x37, 0x18, 0x4b, 0xe7, 0xa0, 0xbf, 0xd5, 0xe0, 0x91, 0x3d, 0x0a, 0xb4, 0xe1,
	0xae, 0xd7, 0x55, 0xcd, 0x06, 0x8a, 0x81, 0x2d, 0xaf, 0x25, 0x15, 0x43, 0x0b, 0x73, 0x6e, 0x68,
	0x91, 0x99, 0xc6, 0xc8, 0x4d, 0xc3, 0xd5, 0xda, 0xcc, 0xd4, 0x8a, 0x13, 0xab, 0xc7, 0x5e, 0xc8,
	0x8b, 0x7a, 0x07, 0x97, 0x48, 0x61, 0xe4, 0x87, 0x4f, 0x32, 0x63, 0xe0, 0x1a, 0x35, 0x8a, 0x94,
	0x12, 0x91, 0x6a, 0xe7, 0x84, 0x74, 0xe1, 0x93, 0xc3, 0x01, 0x10, 0x92, 0x8f, 0x4a, 0x98, 0xd6,
	0x85, 0xc5, 0xf8, 0x24, 0xab, 0xf2, 0x57, 0xe7, 0xab, 0x7c, 0x6e, 0x5f, 0x1e, 0xa1, 0x29, 0x8e,
	0x40, 0xfd, 0x01, 0x51, 0x3b, 0xe5, 0x78, 0xcf, 0xd1, 0x08, 0x26, 0x3f, 0x80, 0xfc, 0xba, 0x66,
	0x73, 0x95, 0x6a, 0x7a, 0xe7, 0x9e, 0x1c, 0x5b, 0xe7, 0x8d, 0xb7, 0x21, 0x1b, 0xef, 0x87, 0xe0,
	0x57, 0x15, 0xaf, 0xdf, 0x9c, 0x09, 0x7c, 0x97, 0x67, 0x38, 0x9e, 0x6f, 0xbe, 0xef, 0x83, 0x03,
	0x65, 0xe3, 0x3d, 0x05, 0xca, 0xdb, 0x8b, 0x67, 0x50, 0x8a, 0x79, 0x56, 0xc0, 0xfe, 0x53, 0x98,
	0x17, 0xaa, 0xd1, 0x2e, 0x9c, 0xd3, 0xe5, 0xb9, 0x2a, 0xcf, 0x1a, 0x4a, 0xcf, 0xb1, 0xbe, 0x33,
	0x32, 0xe6, 0x55, 0x39, 0xb1, 0xb7, 0x70, 0xdc, 0x5d, 0x99, 0x4a, 0x1e, 0x0a, 0x84, 0x7f, 0xf2,
	0x50, 0x20, 0x85, 0x6f, 0x16, 0x85, 0x7f, 0x1d, 0x12, 0x06, 0x31, 0x14, 0x24, 0x84, 0xb1, 0xcc,
	0xd3, 0xce, 0x82, 0xb4, 0xfa, 0x35, 0xe4, 0x84, 0xca, 0xb7, 0xff, 0x81, 0x44, 0xda, 0x52, 0x67,
	0x28, 0xf4, 0xf9, 0xd6, 0x14, 0x6a, 0xfd, 0x32, 0xf5, 0x5b, 0x67, 0x62, 0xb5, 0x2f, 0xa0, 0xb5,
	0xbb, 0x3f, 0xf1, 0x63, 0x4f, 0x31, 0x1f, 0xeb, 0x75, 0x07, 0xe5, 0x11, 0x6a, 0x6d, 0xc9, 0x08,
	0x15, 0x4f, 0xf7, 0x83, 0x28, 0xf4, 0xb3, 0xb1, 0x27, 0x6d, 0xf8, 0x69, 0xfa, 0x94, 0x27, 0x29,
	0x3a, 0x85, 0x8d, 0xf5, 0x07, 0x36, 0x82, 0xcb, 0xc9, 0x6b, 0xfe, 0x21, 0x91, 0x8d, 0xa0, 0x51,
	0x68, 0x04, 0x33, 0xd1, 0x4d, 0x95, 0xe8, 0x0d, 0xe5, 0x7c, 0xb6, 0xa9, 0x64, 0x7f, 0x45, 0xc9,
	0x7e, 0xab, 0xc0, 0x7e, 0x6e, 0xba, 0x76, 0xe9, 0xef, 0x30, 0x3e, 0xa6, 0x77, 0xa1, 0xde, 0x9b,
	0x26, 0x8a, 0x27, 0xd7, 0x5b, 0x2c, 0x59, 0x42, 0xf7, 0x48, 0xb2, 0x86, 0x23, 0x76, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x21, 0xb0, 0xa3, 0x75, 0xfe, 0x1d, 0x00, 0x00,
}
