// Code generated by protoc-gen-main.
// source: gen.go
// DO NOT EDIT!

package robots

import (
	"errors"
	"gotiny/protocol"

	"github.com/golang/protobuf/proto"
)

//解包消息
func unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 3000:
		msg := new(protocol.SBuy)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1002:
		msg := new(protocol.SRegist)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4046:
		msg := new(protocol.SFreeBet)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4101:
		msg := new(protocol.SCreateZiRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1024:
		msg := new(protocol.SGetCurrency)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1060:
		msg := new(protocol.SClassicList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1006:
		msg := new(protocol.SLoginOut)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4016:
		msg := new(protocol.SLaunchVote)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4109:
		msg := new(protocol.SPushDeal)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4108:
		msg := new(protocol.SOperate)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1050:
		msg := new(protocol.SPing)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1054:
		msg := new(protocol.SPrizeDraw)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2003:
		msg := new(protocol.SChatText)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4012:
		msg := new(protocol.SGameover)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4041:
		msg := new(protocol.SFreeCamein)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4043:
		msg := new(protocol.SDealerList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4060:
		msg := new(protocol.SEnterClassicRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4082:
		msg := new(protocol.SPrizeCards)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4102:
		msg := new(protocol.SZiGameover)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4111:
		msg := new(protocol.SPushStatus)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4105:
		msg := new(protocol.SPushDraw)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1020:
		msg := new(protocol.SConfig)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4005:
		msg := new(protocol.SKick)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4044:
		msg := new(protocol.SFreeSit)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4104:
		msg := new(protocol.SZiCamein)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4110:
		msg := new(protocol.SPushDealerDeal)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1022:
		msg := new(protocol.SUserData)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4004:
		msg := new(protocol.SLeave)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4048:
		msg := new(protocol.SFreeGamestart)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4100:
		msg := new(protocol.SEnterZiRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1053:
		msg := new(protocol.SPrizeList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1062:
		msg := new(protocol.SVipList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3004:
		msg := new(protocol.SWxpayQuery)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2006:
		msg := new(protocol.SBroadcast)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1004:
		msg := new(protocol.SWxLogin)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4011:
		msg := new(protocol.SNiu)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4040:
		msg := new(protocol.SEnterFreeRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4080:
		msg := new(protocol.SPubDraw)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4062:
		msg := new(protocol.SClassicGameover)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4081:
		msg := new(protocol.SGetPrize)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4106:
		msg := new(protocol.SPushDiscard)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1055:
		msg := new(protocol.SPrizeBox)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2004:
		msg := new(protocol.SChatVoice)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2008:
		msg := new(protocol.SNotice)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4003:
		msg := new(protocol.SCamein)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4018:
		msg := new(protocol.SVoteResult)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4051:
		msg := new(protocol.SFreeTrend)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4009:
		msg := new(protocol.SPushDealer)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4017:
		msg := new(protocol.SVote)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4042:
		msg := new(protocol.SFreeDealer)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1063:
		msg := new(protocol.SPushVip)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4000:
		msg := new(protocol.SEnterRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4010:
		msg := new(protocol.SBet)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4103:
		msg := new(protocol.SZiGameRecord)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4107:
		msg := new(protocol.SPushAuto)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1052:
		msg := new(protocol.SBankrupts)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3006:
		msg := new(protocol.SApplePay)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4001:
		msg := new(protocol.SCreateRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3002:
		msg := new(protocol.SWxpayOrder)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4006:
		msg := new(protocol.SReady)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4007:
		msg := new(protocol.SDraw)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4050:
		msg := new(protocol.SFreeGameover)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1026:
		msg := new(protocol.SBuildAgent)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3010:
		msg := new(protocol.SShop)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1000:
		msg := new(protocol.SLogin)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4008:
		msg := new(protocol.SDealer)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4020:
		msg := new(protocol.SGameRecord)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1028:
		msg := new(protocol.SPushCurrency)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1030:
		msg := new(protocol.SBank)
		err := proto.Unmarshal(b, msg)
		return msg, err
	default:
		return nil, errors.New("unknown msg")
	}
}
