// Code generated by protoc-gen-main.
// source: gen.go
// DO NOT EDIT!

package socket

import (
	"errors"
	"gotiny/protocol"

	"github.com/golang/protobuf/proto"
)

//解包消息
func unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 4100:
		msg := new(protocol.CEnterZiRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1050:
		msg := new(protocol.CPing)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3006:
		msg := new(protocol.CApplePay)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1000:
		msg := new(protocol.CLogin)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4016:
		msg := new(protocol.CLaunchVote)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4040:
		msg := new(protocol.CEnterFreeRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4081:
		msg := new(protocol.CGetPrize)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4082:
		msg := new(protocol.CPrizeCards)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2003:
		msg := new(protocol.CChatText)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4103:
		msg := new(protocol.CZiGameRecord)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4108:
		msg := new(protocol.COperate)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1030:
		msg := new(protocol.CBank)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1062:
		msg := new(protocol.CVipList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1054:
		msg := new(protocol.CPrizeDraw)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2004:
		msg := new(protocol.CChatVoice)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 2008:
		msg := new(protocol.CNotice)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1004:
		msg := new(protocol.CWxLogin)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4004:
		msg := new(protocol.CLeave)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4008:
		msg := new(protocol.CDealer)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4042:
		msg := new(protocol.CFreeDealer)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4006:
		msg := new(protocol.CReady)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4010:
		msg := new(protocol.CBet)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4044:
		msg := new(protocol.CFreeSit)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1026:
		msg := new(protocol.CBuildAgent)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3010:
		msg := new(protocol.CShop)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1002:
		msg := new(protocol.CRegist)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4001:
		msg := new(protocol.CCreateRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4017:
		msg := new(protocol.CVote)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4046:
		msg := new(protocol.CFreeBet)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4005:
		msg := new(protocol.CKick)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4051:
		msg := new(protocol.CFreeTrend)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4060:
		msg := new(protocol.CEnterClassicRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1060:
		msg := new(protocol.CClassicList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1053:
		msg := new(protocol.CPrizeList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1055:
		msg := new(protocol.CPrizeBox)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3000:
		msg := new(protocol.CBuy)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4020:
		msg := new(protocol.CGameRecord)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4043:
		msg := new(protocol.CDealerList)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4101:
		msg := new(protocol.CCreateZiRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1020:
		msg := new(protocol.CConfig)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1024:
		msg := new(protocol.CGetCurrency)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1052:
		msg := new(protocol.CBankrupts)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3002:
		msg := new(protocol.CWxpayOrder)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 3004:
		msg := new(protocol.CWxpayQuery)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4000:
		msg := new(protocol.CEnterRoom)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4011:
		msg := new(protocol.CNiu)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 4106:
		msg := new(protocol.CPushDiscard)
		err := proto.Unmarshal(b, msg)
		return msg, err
	case 1022:
		msg := new(protocol.CUserData)
		err := proto.Unmarshal(b, msg)
		return msg, err
	default:
		return nil, errors.New("unknown msg")
	}
}
